// Generated by scripts/build.mjs. Edit src/, then run npm run build.

// Mirror Abyss build 4.0.43.

const __ma_module_0 = (() => {
  const KEY = 'mirrorAbyssClean';

  const DEFAULT_SETTINGS = {
    enabled: true,
    autoAudit: false,
    autoExtraction: true,
    autoSmallSummary: true,
    autoLargeSummary: true,
    autoCreateLorebook: true,
    largeSummaryGroups: 4,
    responseTokens: 8192,
    modelProfileId: '',
    auditPrompt: '',
    pageSize: 12,
  };

  function context() {
    const getContext = globalThis.SillyTavern?.getContext;
    if (typeof getContext !== 'function') throw new Error('SillyTavern 尚未就绪');
    return getContext();
  }

  function clone(value) {
    return value == null ? value : JSON.parse(JSON.stringify(value));
  }

  function settings() {
    const ctx = context();
    const saved = ctx.extensionSettings?.[KEY] || {};
    return { ...DEFAULT_SETTINGS, ...saved };
  }

  function saveSettings(patch) {
    const ctx = context();
    ctx.extensionSettings ||= {};
    const next = { ...settings(), ...patch };
    ctx.extensionSettings[KEY] = next;
    ctx.saveSettingsDebounced?.();
    return next;
  }

  function chatId() {
    const ctx = context();
    return String(ctx.getCurrentChatId?.() ?? ctx.chatId ?? '');
  }

  function boundWorldbook() {
    return String(context().chatMetadata?.world_info ?? '').trim();
  }

  async function ensureWorldbook() {
    let name = boundWorldbook();
    const cfg = settings();
    if (name) return name;
    if (!cfg.autoCreateLorebook) throw new Error('当前聊天没有绑定世界书');

    const ctx = context();
    const base = `镜渊-${safeName(chatId() || '世界书')}`;
    const names = await Promise.resolve(ctx.getWorldInfoNames?.() ?? []);
    name = base;
    let index = 2;
    while (names.includes(name)) name = `${base}-${index++}`;

    await ctx.saveWorldInfo(name, { entries: {} }, true);
    ctx.chatMetadata ||= {};
    ctx.chatMetadata.world_info = name;
    await ctx.saveMetadata?.();
    return name;
  }

  async function readWorldbook(name = boundWorldbook()) {
    const target = name || await ensureWorldbook();
    const ctx = context();
    const response = await fetch('/api/worldinfo/get', {
      method: 'POST',
      headers: ctx.getRequestHeaders(),
      cache: 'no-cache',
      body: JSON.stringify({ name: target }),
    });
    if (!response.ok) throw new Error(`读取世界书失败：HTTP ${response.status}`);
    const data = await response.json();
    data.entries ||= {};
    return { name: target, data };
  }

  async function saveWorldbook(name, data) {
    await context().saveWorldInfo(name, data, true);
  }

  function latestAssistant(requested = -1) {
    const chat = context().chat || [];
    let index = Number(requested);
    if (!Number.isInteger(index) || index < 0) {
      index = chat.length - 1;
      while (index >= 0 && (chat[index]?.is_user || chat[index]?.is_system || !String(chat[index]?.mes || '').trim())) index--;
    }
    const message = chat[index];
    if (!message || message.is_user || message.is_system) throw new Error('没有可处理的 AI 正文');
    let playerText = '';
    for (let i = index - 1; i >= 0; i--) {
      if (chat[i]?.is_user) { playerText = String(chat[i].mes || ''); break; }
    }
    return { index, assistantText: String(message.mes || ''), playerText };
  }

  async function replaceAssistant(index, text) {
    const ctx = context();
    const message = ctx.chat?.[index];
    if (!message || message.is_user || message.is_system) throw new Error('AI 正文已经不存在');
    message.mes = String(text || '');
    if (Array.isArray(message.swipes) && Number.isInteger(message.swipe_id)) message.swipes[message.swipe_id] = message.mes;
    ctx.updateMessageBlock?.(index, message);
    await ctx.saveChat?.();
  }

  async function askModel(prompt) {
    const cfg = settings();
    const ctx = context();
    let output;
    if (cfg.modelProfileId && ctx.ConnectionManagerRequestService?.sendRequest) {
      output = await ctx.ConnectionManagerRequestService.sendRequest(
        cfg.modelProfileId,
        [
          { role: 'system', content: String(prompt.system || '') },
          { role: 'user', content: String(prompt.user || '') },
        ],
        Number(cfg.responseTokens) || 8192,
        { stream: false, extractData: true, includePreset: true, includeInstruct: true },
        {},
      );
    } else {
      if (typeof ctx.generateRaw !== 'function') throw new Error('SillyTavern 未提供模型调用接口');
      output = await ctx.generateRaw({
        systemPrompt: String(prompt.system || ''),
        prompt: String(prompt.user || ''),
        responseLength: Number(cfg.responseTokens) || 8192,
        trimNames: false,
      });
    }
    const text = typeof output === 'string'
      ? output
      : output?.content ?? output?.text ?? output?.response ?? output?.choices?.[0]?.message?.content ?? output?.choices?.[0]?.text;
    if (!String(text || '').trim()) throw new Error('模型没有返回内容');
    return String(text).trim();
  }

  function eventTypes() {
    return context().eventTypes || {};
  }

  function onEvent(name, handler) {
    if (!name) return () => {};
    const source = context().eventSource;
    source?.on?.(name, handler);
    return () => source?.removeListener?.(name, handler);
  }

  function messageIndex(value) {
    const raw = typeof value === 'object' ? value?.messageId ?? value?.mesId ?? value?.index : value;
    const number = Number(raw);
    return Number.isInteger(number) && number >= 0 ? number : -1;
  }

  function assistantExists(index) {
    const message = context().chat?.[index];
    return Boolean(message && !message.is_user && !message.is_system && String(message.mes || '').trim());
  }

  function isPendingSwipe(index) {
    const message = context().chat?.[index];
    return Boolean(message && Array.isArray(message.swipes) && Number.isInteger(message.swipe_id) && message.swipe_id >= message.swipes.length);
  }

  function activatedUids(entries) {
    const book = boundWorldbook();
    return (Array.isArray(entries) ? entries : [])
      .filter(entry => !entry?.world || String(entry.world) === book)
      .map(entry => String(entry?.uid ?? ''))
      .filter(Boolean);
  }

  function loadHistory() {
    const raw = context().chatMetadata?.[KEY]?.history;
    return Array.isArray(raw) ? clone(raw) : [];
  }

  async function saveHistory(history) {
    const ctx = context();
    ctx.chatMetadata ||= {};
    ctx.chatMetadata[KEY] ||= {};
    ctx.chatMetadata[KEY].history = clone(history.slice(-120));
    try { await ctx.saveMetadata?.(); }
    catch (error) { console.warn('[Mirror Abyss] 历史记录保存失败', error); }
  }

  async function clearHistory() {
    const ctx = context();
    if (ctx.chatMetadata?.[KEY]) ctx.chatMetadata[KEY].history = [];
    try { await ctx.saveMetadata?.(); }
    catch (error) { console.warn('[Mirror Abyss] 历史记录清理失败', error); }
  }

  function availableProfiles() {
    const service = context().ConnectionManagerRequestService;
    if (!service?.getSupportedProfiles) return [];
    try {
      return (service.getSupportedProfiles() || []).map(profile => ({
        id: String(profile.id),
        name: String(profile.name || profile.id),
      }));
    } catch { return []; }
  }

  function safeName(value) {
    return String(value).replace(/[\\/:*?"<>|]/g, '-').slice(0, 80) || '世界书';
  }
  return Object.freeze({ DEFAULT_SETTINGS, context, clone, settings, saveSettings, chatId, boundWorldbook, ensureWorldbook, readWorldbook, saveWorldbook, latestAssistant, replaceAssistant, askModel, eventTypes, onEvent, messageIndex, assistantExists, isPendingSwipe, activatedUids, loadHistory, saveHistory, clearHistory, availableProfiles });
})();

const __ma_module_1 = (() => {
  const SCHEMA = {
    人物: { icon: '人', replace: ['当前状态'], sections: ['身份', '经历', '当前状态'] },
    场景: { icon: '景', replace: ['状态', '场景阶段'], sections: ['位置', '状态', '场景阶段'] },
    物品: { icon: '物', replace: ['状态', '所属关系'], sections: ['来源', '状态', '所属关系'] },
    事件: { icon: '事', replace: ['事件结果'], sections: ['事件过程', '事件结果', '影响'] },
    世界: { icon: '界', replace: ['环境状态'], sections: ['世界规则', '环境状态', '长期变化'] },
    基础设定: { icon: '基', replace: [], sections: ['世界常识', '自然规则', '种族与生命', '能力与技术', '社会规则', '地理框架', '别名'] },
  };

  const schemaText = Object.entries(SCHEMA).map(([type, value]) => `${type}：${value.sections.join('、')}`).join('\n');
  const finalOnly = '只输出规定格式，不解释，不输出分析，不使用代码块。';

  function extractionPrompt(playerText, assistantText, entries, currentScene = '') {
    const book = entries.map(entry => `${entry.title}\n${entry.content}`).join('\n\n') || '（无）';
    return {
      system: `你是世界事实整理员。只记录当前AI正文中已经明确发生、会影响后续连续性的事实。不预测，不补全，不把玩家愿望当事实。已有对象必须复用世界书里的“类型｜稳定名称”。\n\n允许类型与栏目：\n${schemaText}\n\n第一行：当前场景｜稳定名称/未识别\n每个对象先写：关键词｜类型｜稳定名称｜关键词1、关键词2、关键词3\n每条事实写：事实｜类型｜稳定名称｜栏目｜关联对象｜完整事实\n多个关联对象用“、”分隔。没有事实时，场景行后只写“无”。\n${finalOnly}`,
      user: `提取前当前场景：${currentScene || '未识别'}\n\n提取前世界书：\n${book}\n\n玩家本轮输入：\n${playerText || '（无）'}\n\n当前AI正文：\n${assistantText}`,
    };
  }

  function summaryPrompt(kind, entries, requirement = '') {
    const label = kind === 'large' ? '长期大总结' : kind === 'merge' ? '人工合并' : '当前场景小总结';
    const source = entries.map((entry, index) => `条目${index + 1}\n${entry.title}\n${entry.content}`).join('\n\n');
    return {
      system: `${label}。只整理来源中已经存在的事实，不新增事实。允许把多个来源合并成更少、更完整的条目。\n\n允许类型与栏目：\n${schemaText}\n\n每条输出：整理｜条目编号（可多个，用、分隔）｜类型｜稳定名称｜栏目｜完整事实\n必须覆盖全部来源。${kind === 'merge' ? '人工合并后的目标数必须少于来源数。' : ''}\n${finalOnly}`,
      user: `${requirement ? `玩家要求：${requirement}\n\n` : ''}来源：\n${source}`,
    };
  }

  function importPrompt(text, entries) {
    const book = entries.map(entry => `${entry.title}\n${entry.content}`).join('\n\n') || '（无）';
    return {
      system: `把玩家提交的世界设定整理为世界书条目。世界长期通用规则优先放入“基础设定”，具体人物、场景、物品、事件、世界状态按对应类型整理。导入条目之后会由插件设为基石。\n\n允许类型与栏目：\n${schemaText}\n\n每个对象先写：关键词｜类型｜稳定名称｜关键词1、关键词2、关键词3\n每条事实写：事实｜类型｜稳定名称｜栏目｜关联对象｜完整事实\n没有可导入内容时只写“无”。\n${finalOnly}`,
      user: `玩家提交的世界设定：\n${text}\n\n已有世界书：\n${book}`,
    };
  }

  function auditPrompt(text, rules) {
    return {
      system: `${rules}\n\n符合要求只输出：审核结论：通过\n不符合只输出：\n审核结论：需要修正\n- 明确问题\n${finalOnly}`,
      user: `待审核正文：\n${text}`,
    };
  }

  function revisionPrompt(text, issues) {
    return {
      system: `只修正列出的明确问题，其他内容保持不变。直接输出修改后的完整正文。${finalOnly}`,
      user: `问题：\n${issues.map(item => `- ${item}`).join('\n')}\n\n原正文：\n${text}`,
    };
  }
  return Object.freeze({ SCHEMA, extractionPrompt, summaryPrompt, importPrompt, auditPrompt, revisionPrompt });
})();

const __ma_module_2 = (() => {
  const { SCHEMA } = __ma_module_1;
  const { clone } = __ma_module_0;
  const TITLE = /^(人物|场景|物品|事件|世界|基础设定)｜(.+)$/u;
  const FACT = /^事实｜([^｜]+)｜([^｜]+)｜([^｜]+)｜([^｜]*)｜(.+)$/u;
  const KEYWORDS = /^关键词｜([^｜]+)｜([^｜]+)｜(.+)$/u;
  const SUMMARY = /^整理｜([^｜]+)｜([^｜]+)｜([^｜]+)｜([^｜]+)｜(.+)$/u;

  function parseExtraction(text, previousScene = '') {
    const lines = cleanLines(text);
    if (!lines.length || !lines[0].startsWith('当前场景｜')) throw new Error('模型返回格式不符合提取约定');
    let scene = lines.shift().slice('当前场景｜'.length).trim();
    if (!scene || scene === '未识别') scene = previousScene || '';
    if (lines.length === 1 && lines[0] === '无') return { scene, groups: [] };
    return { scene, groups: parseFactLines(lines) };
  }

  function parseImport(text) {
    const lines = cleanLines(text);
    if (lines.length === 1 && lines[0] === '无') return [];
    return parseFactLines(lines);
  }

  function parseSummary(text, sources) {
    const lines = cleanLines(text);
    const groups = new Map();
    for (const line of lines) {
      const match = line.match(SUMMARY);
      if (!match) throw new Error('模型返回格式不符合总结约定');
      const refs = match[1].split(/[、,，]/u).map(value => value.trim()).filter(Boolean);
      const indexes = refs.map(ref => Number(ref.replace('条目', '')) - 1);
      if (indexes.some(index => index < 0 || index >= sources.length)) throw new Error('模型返回了不存在的条目编号');
      const type = match[2].trim();
      const name = match[3].trim();
      const section = match[4].trim();
      const fact = match[5].trim();
      if (!SCHEMA[type]) throw new Error('模型返回了未知条目类型');
      const key = `${indexes.join(',')}|${type}｜${name}`;
      const group = groups.get(key) || { indexes, type, name, title: `${type}｜${name}`, sections: {} };
      group.sections[section] ||= [];
      if (!group.sections[section].includes(fact)) group.sections[section].push(fact);
      groups.set(key, group);
    }
    return [...groups.values()];
  }

  function parseAudit(text) {
    const value = String(text || '').trim();
    if (value === '审核结论：通过') return { passed: true, issues: [] };
    const lines = value.split(/\r?\n/u).map(line => line.trim()).filter(Boolean);
    if (lines[0] !== '审核结论：需要修正') throw new Error('模型返回格式不符合审核约定');
    return { passed: false, issues: lines.slice(1).map(line => line.replace(/^[-•]\s*/u, '')).filter(Boolean) };
  }

  function managedEntries(data) {
    const result = [];
    for (const raw of Object.values(data.entries || {})) {
      const title = String(raw?.comment || '').trim().match(TITLE);
      if (!title || raw?.extensions?.mirrorAbyss?.managed !== true) continue;
      const ext = raw.extensions.mirrorAbyss;
      result.push({
        uid: String(raw.uid),
        type: title[1],
        name: title[2].trim(),
        title: `${title[1]}｜${title[2].trim()}`,
        content: stripRelationBlock(raw.content),
        keywords: unique(raw.key),
        folder: String(ext.folder || ''),
        cornerstone: ext.cornerstone === true,
        focus: ext.focus === true,
        insertionPosition: Number(ext.insertionPosition ?? raw.position ?? 1) === 0 ? 0 : 1,
        scene: String(ext.scene || ''),
        messageIndex: Number(ext.messageIndex ?? -1),
        updatedAt: Number(ext.updatedAt || 0),
        summaryLevel: String(ext.summaryLevel || ''),
        summaryBatch: Number(ext.summaryBatch || 0),
        constant: raw.constant === true,
        secondaryKeywords: unique(raw.keysecondary),
        raw,
      });
    }
    return result.sort((a, b) => a.type.localeCompare(b.type, 'zh-CN') || a.name.localeCompare(b.name, 'zh-CN'));
  }

  function currentScene(entries) {
    return [...entries]
      .filter(entry => entry.scene)
      .sort((a, b) => b.updatedAt - a.updatedAt)[0]?.scene || '';
  }

  function applyFacts(data, groups, options = {}) {
    const changes = [];
    const touched = [];
    for (const group of groups) {
      const title = `${group.type}｜${group.name}`;
      let raw = findByTitle(data, title);
      if (raw?.extensions?.mirrorAbyss?.cornerstone && options.automatic) continue;
      if (!raw) {
        raw = createEntry(data);
        remember(changes, raw.uid, null);
      } else {
        remember(changes, raw.uid, raw);
      }

      const sections = parseSections(raw.content);
      for (const row of group.rows) {
        const oldFacts = sections[row.section] || [];
        if (SCHEMA[group.type]?.replace?.includes(row.section)) sections[row.section] = [row.fact];
        else sections[row.section] = unique([...oldFacts, row.fact]);
      }

      fillEntry(raw, group.type, group.name, sections, group.keywords, {
        messageIndex: options.messageIndex,
        scene: options.scene,
        summaryLevel: '',
        summaryBatch: 0,
      });
      raw.extensions.mirrorAbyss.relations = unique(group.rows.flatMap(row => row.relations));
      touched.push(String(raw.uid));
    }
    return { changes, touched: unique(touched) };
  }

  function applySummary(data, sources, groups, options = {}) {
    const changes = [];
    const touched = [];
    const sourceUids = new Set(sources.map(entry => String(entry.uid)));

    for (const group of groups) {
      const groupSources = group.indexes.map(index => sources[index]).filter(Boolean);
      if (!groupSources.length) continue;
      for (const source of groupSources) remember(changes, source.uid, source.raw);

      let target = managedEntries(data).find(entry => entry.title === group.title && !sourceUids.has(String(entry.uid)));
      if (target?.cornerstone && options.automatic) target = null;
      if (target) remember(changes, target.uid, target.raw);

      const targetUid = target?.uid || groupSources[0].uid;
      for (const source of groupSources) {
        if (String(source.uid) !== String(targetUid)) delete data.entries[source.uid];
      }

      let raw = data.entries[targetUid];
      if (!raw) {
        raw = clone(groupSources[0].raw);
        raw.uid = Number.isNaN(Number(targetUid)) ? targetUid : Number(targetUid);
        data.entries[targetUid] = raw;
      }

      const keywords = unique(groupSources.flatMap(entry => entry.keywords));
      fillEntry(raw, group.type, group.name, group.sections, keywords, {
        messageIndex: options.messageIndex,
        scene: groupSources.map(entry => entry.scene).find(Boolean) || '',
        summaryLevel: options.kind || 'small',
        summaryBatch: Date.now(),
      });
      touched.push(String(raw.uid));
    }
    return { changes: dedupeChanges(changes), touched: unique(touched) };
  }

  function rollbackChanges(data, changes) {
    for (const change of [...changes].reverse()) {
      if (change.before == null) delete data.entries[change.uid];
      else data.entries[change.uid] = clone(change.before);
    }
  }


  function updateEntry(data, uid, content) {
    const raw = data.entries?.[uid];
    if (!raw) throw new Error(`找不到 UID ${uid}`);
    const changes = [{ uid: String(uid), before: clone(raw) }];
    raw.content = String(content || '').trim();
    raw.extensions ||= {};
    raw.extensions.mirrorAbyss ||= { managed: true };
    raw.extensions.mirrorAbyss.updatedAt = Date.now();
    raw.extensions.mirrorAbyss.messageIndex = -1;
    return { changes, touched: [String(uid)] };
  }

  function setCornerstone(data, uids, locked) {
    return changeEntries(data, uids, raw => {
      raw.extensions ||= {};
      raw.extensions.mirrorAbyss ||= { managed: true };
      raw.extensions.mirrorAbyss.cornerstone = Boolean(locked);
    });
  }

  function setFocus(data, uid, focused) {
    const entries = managedEntries(data);
    const target = entries.find(entry => String(entry.uid) === String(uid));
    if (!target || target.type !== '人物') throw new Error('只有人物条目可以设为焦点');
    const affected = entries.filter(entry => entry.type === '人物' && (entry.focus || String(entry.uid) === String(uid))).map(entry => entry.uid);
    return changeEntries(data, affected, raw => {
      const yes = String(raw.uid) === String(uid) && Boolean(focused);
      raw.extensions.mirrorAbyss.focus = yes;
      if (yes) raw.constant = true;
    });
  }

  function setInsertionPosition(data, uids, position) {
    return changeEntries(data, uids, raw => {
      const value = Number(position) === 0 ? 0 : 1;
      raw.position = value;
      raw.extensions ||= {};
      raw.extensions.mirrorAbyss ||= { managed: true };
      raw.extensions.mirrorAbyss.insertionPosition = value;
    });
  }

  function setFolder(data, uids, folder) {
    return changeEntries(data, uids, raw => {
      raw.extensions ||= {};
      raw.extensions.mirrorAbyss ||= { managed: true };
      raw.extensions.mirrorAbyss.folder = String(folder || '').trim();
    });
  }

  function updateRecall(data, uid, value) {
    return changeEntries(data, [uid], raw => {
      const title = String(raw.comment || '').match(TITLE);
      const name = title?.[2]?.trim() || '';
      raw.key = unique([name, raw.comment, ...(value.keywords || [])]);
      raw.keysecondary = unique(value.secondaryKeywords || []);
      raw.constant = Boolean(value.constant);
    });
  }

  function deleteEntries(data, uids) {
    const changes = [];
    for (const uid of uids) {
      const raw = data.entries?.[uid];
      if (!raw) continue;
      remember(changes, uid, raw);
      delete data.entries[uid];
    }
    return { changes, touched: unique(uids.map(String)) };
  }

  function setGameTime(data, value) {
    const title = '世界｜游戏时间';
    let raw = findByTitle(data, title);
    const changes = [];
    if (!raw) {
      raw = createEntry(data);
      remember(changes, raw.uid, null);
    } else remember(changes, raw.uid, raw);
    fillEntry(raw, '世界', '游戏时间', { 环境状态: [`当前游戏时间：${String(value || '').trim()}`] }, ['游戏时间'], {});
    return { changes, touched: [String(raw.uid)] };
  }

  function migrateOldEntries(data) {
    const changes = [];
    const touched = [];
    for (const raw of Object.values(data.entries || {})) {
      if (raw?.extensions?.mirrorAbyss?.managed === true) continue;
      const title = String(raw?.comment || '').trim().match(TITLE);
      if (!title) continue;
      remember(changes, raw.uid, raw);
      raw.extensions ||= {};
      raw.extensions.mirrorAbyss = {
        managed: true,
        cornerstone: false,
        focus: false,
        folder: '',
        insertionPosition: Number(raw.position) === 0 ? 0 : 1,
        scene: '',
        messageIndex: -1,
        updatedAt: Date.now(),
      };
      touched.push(String(raw.uid));
    }
    return { changes, touched };
  }

  function smallSummarySources(entries, scene) {
    return entries.filter(entry => entry.scene === scene && !entry.cornerstone && entry.summaryLevel !== 'small' && entry.summaryLevel !== 'large');
  }

  function largeSummarySources(entries, groupCount = 4) {
    const small = entries.filter(entry => entry.summaryLevel === 'small' && !entry.cornerstone);
    const batches = unique(small.map(entry => entry.summaryBatch).filter(Boolean)).slice(0, Math.max(2, Number(groupCount) || 4));
    return small.filter(entry => batches.includes(entry.summaryBatch));
  }

  function overview(entries) {
    const byType = {};
    const byFolder = {};
    for (const entry of entries) {
      byType[entry.type] = (byType[entry.type] || 0) + 1;
      const folder = entry.folder || '默认分类';
      byFolder[folder] = (byFolder[folder] || 0) + 1;
    }
    return { total: entries.length, byType, byFolder };
  }

  function parseFactLines(lines) {
    const groups = new Map();
    for (const line of lines) {
      const keyword = line.match(KEYWORDS);
      if (keyword) {
        const type = keyword[1].trim();
        const name = keyword[2].trim();
        if (!SCHEMA[type]) throw new Error('模型返回了未知条目类型');
        const key = `${type}｜${name}`;
        const group = groups.get(key) || { type, name, title: key, keywords: [], rows: [] };
        group.keywords = unique([...group.keywords, ...keyword[3].split(/[、,，]/u)]);
        groups.set(key, group);
        continue;
      }
      const fact = line.match(FACT);
      if (!fact) throw new Error('模型返回格式不符合事实约定');
      const type = fact[1].trim();
      const name = fact[2].trim();
      if (!SCHEMA[type]) throw new Error('模型返回了未知条目类型');
      const key = `${type}｜${name}`;
      const group = groups.get(key) || { type, name, title: key, keywords: [], rows: [] };
      group.rows.push({ section: fact[3].trim(), relations: fact[4].split(/[、,，]/u).map(value => value.trim()).filter(Boolean), fact: fact[5].trim() });
      groups.set(key, group);
    }
    return [...groups.values()];
  }

  function createEntry(data) {
    let uid = 0;
    while (Object.hasOwn(data.entries, uid)) uid++;
    const raw = {
      uid,
      key: [], keysecondary: [], comment: '', content: '',
      constant: false, vectorized: false, selective: true, selectiveLogic: 0,
      addMemo: false, order: 100, position: 1, disable: false, ignoreBudget: false,
      excludeRecursion: true, preventRecursion: true,
      matchPersonaDescription: false, matchCharacterDescription: false, matchCharacterPersonality: false,
      matchCharacterDepthPrompt: false, matchScenario: false, matchCreatorNotes: false,
      delayUntilRecursion: 0, probability: 100, useProbability: true, depth: 4,
      outletName: '', group: '', groupOverride: false, groupWeight: 100,
      scanDepth: null, caseSensitive: null, matchWholeWords: null, useGroupScoring: null,
      automationId: '', role: 0, sticky: null, cooldown: null, delay: null, triggers: [], extensions: {},
    };
    data.entries[uid] = raw;
    return raw;
  }

  function fillEntry(raw, type, name, sections, keywords = [], extra = {}) {
    raw.comment = `${type}｜${name}`;
    raw.content = serializeSections(sections);
    raw.key = unique([name, raw.comment, ...keywords]);
    raw.keysecondary = unique(raw.keysecondary);
    raw.selective = true;
    raw.selectiveLogic = 0;
    raw.excludeRecursion = true;
    raw.preventRecursion = true;
    raw.depth = 4;
    raw.position = Number(raw?.extensions?.mirrorAbyss?.insertionPosition ?? raw.position ?? 1) === 0 ? 0 : 1;
    raw.order = orderFor(type, extra.messageIndex);
    raw.extensions ||= {};
    const old = raw.extensions.mirrorAbyss || {};
    raw.extensions.mirrorAbyss = {
      ...old,
      managed: true,
      cornerstone: old.cornerstone === true,
      focus: old.focus === true,
      folder: String(old.folder || ''),
      insertionPosition: raw.position,
      scene: String(extra.scene ?? old.scene ?? ''),
      messageIndex: Number(extra.messageIndex ?? old.messageIndex ?? -1),
      updatedAt: Date.now(),
      summaryLevel: String(extra.summaryLevel ?? old.summaryLevel ?? ''),
      summaryBatch: Number(extra.summaryBatch ?? old.summaryBatch ?? 0),
    };
    if (type === '基础设定' || old.focus === true) raw.constant = true;
  }

  function parseSections(content) {
    const result = {};
    let section = '';
    for (const rawLine of stripRelationBlock(content).split(/\r?\n/u)) {
      const line = rawLine.trim();
      const heading = line.match(/^【(.+)】$/u);
      if (heading) { section = heading[1].trim(); result[section] ||= []; continue; }
      const fact = line.match(/^-\s*(.+)$/u);
      if (fact && section) result[section].push(fact[1].trim());
    }
    return result;
  }

  function serializeSections(sections) {
    const lines = [];
    for (const [section, facts] of Object.entries(sections || {})) {
      const values = unique(facts);
      if (!values.length) continue;
      lines.push(`【${section}】`, ...values.map(fact => `- ${fact}`), '');
    }
    return lines.join('\n').trim();
  }

  function stripRelationBlock(content) {
    return String(content || '').split(/\n【镜渊关系】\n/u)[0].trim();
  }

  function findByTitle(data, title) {
    return Object.values(data.entries || {}).find(raw => raw?.extensions?.mirrorAbyss?.managed === true && String(raw.comment || '').trim() === title);
  }

  function orderFor(type, messageIndex = -1) {
    const base = { 基础设定: 0, 世界: 1000, 场景: 2000, 人物: 3000, 物品: 4000, 事件: 5000 }[type] || 6000;
    const index = Number(messageIndex);
    return base + (Number.isInteger(index) && index >= 0 ? Math.min(index, 999) : 0);
  }

  function changeEntries(data, uids, mutator) {
    const changes = [];
    const touched = [];
    for (const uid of uids) {
      const raw = data.entries?.[uid];
      if (!raw) continue;
      remember(changes, uid, raw);
      mutator(raw);
      raw.extensions.mirrorAbyss.updatedAt = Date.now();
      touched.push(String(uid));
    }
    return { changes, touched };
  }

  function remember(changes, uid, before) {
    const key = String(uid);
    if (changes.some(change => change.uid === key)) return;
    changes.push({ uid: key, before: before == null ? null : clone(before) });
  }

  function dedupeChanges(changes) {
    const map = new Map();
    for (const change of changes) if (!map.has(change.uid)) map.set(change.uid, change);
    return [...map.values()];
  }


  function cleanLines(text) {
    return String(text || '')
      .replace(/<think>[\s\S]*?<\/think>/giu, '')
      .replace(/```(?:\w+)?/gu, '')
      .split(/\r?\n/u)
      .map(line => line.trim())
      .filter(Boolean);
  }

  function unique(values) {
    return [...new Set((values || []).map(value => String(value || '').trim()).filter(Boolean))];
  }
  return Object.freeze({ parseExtraction, parseImport, parseSummary, parseAudit, managedEntries, currentScene, applyFacts, applySummary, rollbackChanges, updateEntry, setCornerstone, setFocus, setInsertionPosition, setFolder, updateRecall, deleteEntries, setGameTime, migrateOldEntries, smallSummarySources, largeSummarySources, overview });
})();

const __ma_module_3 = (() => {
  const { SCHEMA } = __ma_module_1;
  function mountUI(api) {
    let activeTab = 'run';
    let expandedUid = '';
    let search = '';
    let folder = '';
    const selected = new Set();

    const root = document.body || document.documentElement;

    const launcher = el('button', 'ma-launcher', '镜');
    launcher.type = 'button';
    launcher.title = '镜渊 · 世界记忆';
    // Fallback layout: the launcher stays visible even if the stylesheet fails.
    launcher.style.cssText = 'position:fixed;right:14px;bottom:82px;z-index:2147483000;width:52px;height:52px;border-radius:18px;border:1px solid rgba(0,0,0,.12);background:rgba(255,255,255,.88);color:#222;font-size:18px;font-weight:700;';
    root.append(launcher);

    // Keep the proven old-style window skeleton: header / tabs / content.
    // The game feeling comes from CSS only, so the DOM stays boring and reliable.
    const panel = el('section', 'ma-root ma-panel');
    panel.hidden = false;
    panel.innerHTML = `
      <div class="ma-window">
        <div class="ma-atmosphere" aria-hidden="true">
          <i></i><i></i><i></i>
        </div>
        <header class="ma-header">
          <div class="ma-brand">
            <span class="ma-brand-mark">镜</span>
            <span class="ma-brand-copy">
              <strong>镜渊</strong>
              <small>世界记忆</small>
            </span>
          </div>
          <button type="button" class="ma-close" data-close aria-label="关闭">×</button>
        </header>
        <nav class="ma-tabs" aria-label="镜渊功能"></nav>
        <main class="ma-main"></main>
      </div>`;
    root.append(panel);

    const tabs = panel.querySelector('.ma-tabs');
    const main = panel.querySelector('.ma-main');
    const tabNames = [['run', '旅程'], ['notes', '档案'], ['import', '设定'], ['settings', '选项']];
    for (const [id, label] of tabNames) {
      const button = btn(label, () => { activeTab = id; render(); });
      button.dataset.tab = id;
      tabs.append(button);
    }

    launcher.addEventListener('click', () => {
      panel.hidden = false;
      document.documentElement.classList.add('ma-panel-open');
      render();
    });
    panel.querySelector('[data-close]').addEventListener('click', close);

    async function render() {
      if (panel.hidden) return;
      for (const button of tabs.querySelectorAll('[data-tab]')) button.classList.toggle('is-active', button.dataset.tab === activeTab);
      main.replaceChildren();
      if (activeTab === 'run') renderRun();
      if (activeTab === 'notes') await renderNotes();
      if (activeTab === 'import') renderImport();
      if (activeTab === 'settings') renderSettings();
    }

    function renderRun() {
      const view = api.state();
      const hero = el('section', 'ma-story-hero', [
        el('h1', 'ma-scene-title', view.currentScene || '等待故事继续'),
        el('div', 'ma-story-rule'),
        el('small', 'ma-worldbook-name', `世界书 · ${view.worldbookName || '未绑定'}`),
      ]);
      const choices = section('选择', el('div', 'ma-choice-list', [
        taskButton('整理当前正文', () => api.process('full'), 'ma-choice'),
        taskButton('仅提取世界事实', () => api.process('extract'), 'ma-choice'),
        taskButton('审核当前正文', () => api.process('audit'), 'ma-choice ma-choice-secondary'),
        taskButton('结算当前场景', () => api.summarize('small'), 'ma-choice ma-choice-secondary'),
        taskButton('整理长期记忆', () => api.summarize('large'), 'ma-choice ma-choice-secondary'),
        view.busy ? btn('中止当前任务', () => api.cancel(), 'ma-choice ma-danger') : null,
      ].filter(Boolean)));
      main.append(hero, choices, statusBlock(view));
    }

    async function renderNotes() {
      const loading = section('世界档案', el('div', 'ma-empty', '读取中…'));
      main.append(loading);
      try {
        const opened = await api.listEntries();
        if (activeTab !== 'notes') return;
        main.replaceChildren();
        const entries = opened.entries;
        const folders = [...new Set(entries.map(entry => entry.folder).filter(Boolean))];

        const toolbar = el('section', 'ma-archive-toolbar');
        toolbar.append(el('div', 'ma-archive-title', [el('h1', '', '世界档案'), el('span', 'ma-folder-count', `${entries.length} 条记录`)]));
        const searchInput = input('搜索名称/正文', search);
        searchInput.addEventListener('input', () => { search = searchInput.value; void renderNotes(); });
        const folderSelect = select([['', '全部文件夹'], ...folders.map(name => [name, name])], folder);
        folderSelect.addEventListener('change', () => { folder = folderSelect.value; void renderNotes(); });
        toolbar.append(el('div', 'ma-filter-row', [searchInput, folderSelect]));

        if (selected.size) {
          const bar = el('div', 'ma-manage-bar', [
            el('div', 'ma-selection-status', `已选择 ${selected.size} 个条目`),
            el('div', 'ma-manage-actions', [
              taskButton('人工合并', () => api.summarize('merge', [...selected])),
              taskButton('设为基石', () => api.setCornerstone([...selected], true)),
              taskButton('解除基石', () => api.setCornerstone([...selected], false)),
              taskButton('移动文件夹', async () => {
                const name = prompt('输入文件夹名称；留空回到默认分类', '') ?? null;
                if (name !== null) await api.setFolder([...selected], name);
              }),
              taskButton('定义前', () => api.setInsertionPosition([...selected], 0)),
              taskButton('定义后', () => api.setInsertionPosition([...selected], 1)),
              taskButton('删除', async () => {
                if (confirm(`删除 ${selected.size} 个条目？`)) await api.deleteEntries([...selected]);
              }, 'ma-danger'),
            ]),
          ]);
          toolbar.append(bar);
        }
        main.append(toolbar);

        const filtered = entries.filter(entry => {
          const hitSearch = !search || `${entry.title}\n${entry.content}`.toLowerCase().includes(search.toLowerCase());
          const hitFolder = !folder || entry.folder === folder;
          return hitSearch && hitFolder;
        });
        const grouped = new Map();
        for (const entry of filtered) {
          const key = entry.folder || '默认分类';
          if (!grouped.has(key)) grouped.set(key, []);
          grouped.get(key).push(entry);
        }
        if (!filtered.length) main.append(el('div', 'ma-empty', '没有条目'));
        for (const [name, values] of grouped) main.append(folderBlock(name, values));
      } catch (error) {
        main.replaceChildren(section('世界档案', el('div', 'ma-error', String(error?.message || error))));
      }
    }

    function folderBlock(name, entries) {
      const block = el('section', 'ma-folder');
      block.append(el('div', 'ma-folder-head', [el('h2', '', name), el('span', 'ma-folder-count', `${entries.length} 条`)]));
      for (const entry of entries) block.append(entryCard(entry));
      return block;
    }

    function entryCard(entry) {
      const expanded = String(entry.uid) === expandedUid;
      const card = el('article', `ma-entry-item${expanded ? ' is-expanded' : ''}`);
      const checkbox = document.createElement('input');
      checkbox.type = 'checkbox';
      checkbox.checked = selected.has(String(entry.uid));
      checkbox.addEventListener('change', () => {
        if (checkbox.checked) selected.add(String(entry.uid)); else selected.delete(String(entry.uid));
        void renderNotes();
      });
      checkbox.className = 'ma-entry-check';
      const icon = el('span', 'ma-type-icon', SCHEMA[entry.type]?.icon || '·');
      const copy = el('span', 'ma-entry-copy', [
        el('strong', '', entry.name),
        el('small', 'ma-entry-status', `${entry.type}${entry.cornerstone ? ' · 基石' : ''}${entry.focus ? ' · 焦点' : ''}${entry.summaryLevel ? ` · ${entry.summaryLevel}` : ''}`),
        el('small', 'ma-keywords', `关键词：${entry.keywords.join('、') || '无'}`),
      ]);
      const open = btn(expanded ? '收起' : '展开', () => { expandedUid = expanded ? '' : String(entry.uid); void renderNotes(); }, 'ma-quiet ma-entry-open');
      card.append(el('div', 'ma-entry-row', [checkbox, icon, copy, open]));
      if (expanded) card.append(entryDetail(entry));
      return card;
    }

    function entryDetail(entry) {
      const body = el('div', 'ma-detail-body');
      body.append(el('small', 'ma-detail-meta', `UID ${entry.uid} · ${entry.insertionPosition === 0 ? '角色定义前' : '角色定义后'}${entry.folder ? ` · ${entry.folder}` : ''}`));
      const editor = document.createElement('textarea');
      editor.className = 'ma-input ma-editor';
      editor.value = entry.content;
      body.append(editor);

      const buttons = el('div', 'ma-detail-toolbar', [
        taskButton('保存正文', () => api.updateEntry(entry.uid, editor.value)),
        taskButton(entry.cornerstone ? '解除基石' : '设为基石', () => api.setCornerstone([entry.uid], !entry.cornerstone)),
        entry.type === '人物' ? taskButton(entry.focus ? '解除焦点' : '设为焦点', () => api.setFocus(entry.uid, !entry.focus)) : null,
        taskButton('定义前', () => api.setInsertionPosition([entry.uid], 0)),
        taskButton('定义后', () => api.setInsertionPosition([entry.uid], 1)),
        taskButton('移动文件夹', async () => {
          const name = prompt('输入文件夹名称；留空回到默认分类', entry.folder) ?? null;
          if (name !== null) await api.setFolder([entry.uid], name);
        }),
        taskButton('删除', async () => { if (confirm(`删除 ${entry.title}？`)) await api.deleteEntries([entry.uid]); }, 'ma-danger'),
      ].filter(Boolean));
      body.append(buttons);

      const keywords = input('主要关键词，用、分隔', entry.keywords.join('、'));
      const secondary = input('次关键词，用、分隔', entry.secondaryKeywords.join('、'));
      const constant = document.createElement('input'); constant.type = 'checkbox'; constant.checked = entry.constant;
      const recall = el('div', 'ma-entry-settings', [
        el('strong', '', '召回'), keywords, secondary,
        el('label', 'ma-check-field', [constant, span('常驻')]),
        taskButton('保存召回', () => api.updateRecall(entry.uid, {
          keywords: splitKeywords(keywords.value),
          secondaryKeywords: splitKeywords(secondary.value),
          constant: constant.checked,
        })),
      ]);
      body.append(recall);
      return body;
    }

    function renderImport() {
      const text = document.createElement('textarea');
      text.className = 'ma-input ma-import-text';
      text.placeholder = '粘贴世界设定，或把 TXT 内容复制到这里';
      main.append(section('写入世界', [
        el('p', 'ma-page-intro', '把世界设定交给模型整理，然后直接写进当前世界书。'),
        text,
        el('p', 'ma-help', '导入后的条目自动设为基石。'),
        taskButton('整理并导入', () => api.importText(text.value)),
      ]));
    }

    function renderSettings() {
      const cfg = api.settings();
      main.append(el('div', 'ma-options-head', [el('h1', '', '选项')]));
      const host = section('自动运行');
      host.append(toggle('自动提取', cfg.autoExtraction, value => api.saveSettings({ autoExtraction: value })));
      host.append(toggle('自动审核', cfg.autoAudit, value => api.saveSettings({ autoAudit: value })));
      host.append(toggle('自动小总结', cfg.autoSmallSummary, value => api.saveSettings({ autoSmallSummary: value })));
      host.append(toggle('自动大总结', cfg.autoLargeSummary, value => api.saveSettings({ autoLargeSummary: value })));
      host.append(toggle('未绑定时自动建世界书', cfg.autoCreateLorebook, value => api.saveSettings({ autoCreateLorebook: value })));

      const model = section('模型');
      const profiles = api.profiles();
      const profileSelect = select([['', '使用当前 SillyTavern 模型'], ...profiles.map(profile => [String(profile.id), String(profile.name || profile.id)])], cfg.modelProfileId);
      profileSelect.addEventListener('change', () => api.saveSettings({ modelProfileId: profileSelect.value }));
      const tokens = input('最大输出 Tokens', String(cfg.responseTokens), 'number');
      tokens.addEventListener('change', () => api.saveSettings({ responseTokens: Number(tokens.value) || 8192 }));
      const groups = input('大总结触发批次数', String(cfg.largeSummaryGroups), 'number');
      groups.addEventListener('change', () => api.saveSettings({ largeSummaryGroups: Number(groups.value) || 4 }));
      const audit = document.createElement('textarea');
      audit.className = 'ma-input ma-small-editor';
      audit.placeholder = '审核提示词';
      audit.value = cfg.auditPrompt || '';
      audit.addEventListener('change', () => api.saveSettings({ auditPrompt: audit.value }));
      model.append(profileSelect, tokens, groups, audit, taskButton('测试模型', () => api.testModel()));

      const maintenance = section('维护', grid([
        taskButton('迁移旧格式条目', () => api.migrate()),
        taskButton('撤回上次手动操作', () => api.undo()),
        taskButton('清空镜渊管理条目', async () => { if (confirm('确定清空当前世界书中的镜渊管理条目？')) await api.reset(); }, 'ma-danger'),
      ]));
      main.append(host, model, maintenance);
    }

    function statusBlock(view) {
      const block = section('运行记录');
      const text = view.error ? `${view.status} · ${view.error}` : view.status;
      block.append(el('div', `ma-status${view.error ? ' is-error' : ''}`, text));
      if (view.busy) block.append(el('small', 'ma-help', '任务正在运行')); 
      if (view.undo) block.append(el('div', 'ma-inline-actions', [span(`可撤回：${view.undo.label}`), taskButton('撤回', () => api.undo(), 'ma-mini ma-quiet')]));
      if (view.activatedUids?.length) block.append(el('div', 'ma-activated-row', [
        el('strong', '', '本轮实际激活'),
        ...view.activatedUids.map(uid => btn(`UID ${uid}`, () => showEntry(uid), 'ma-mini ma-quiet')),
      ]));
      if (view.lastResult?.uids?.length) block.append(el('small', 'ma-help', `本次更新：${view.lastResult.uids.join('、')}`));
      return block;
    }

    function toggle(label, checked, change) {
      const inputEl = document.createElement('input');
      inputEl.type = 'checkbox'; inputEl.checked = checked;
      inputEl.addEventListener('change', () => change(inputEl.checked));
      return el('label', 'ma-setting-row', [span(label), inputEl]);
    }

    function taskButton(label, action, className = '') {
      return btn(label, async event => {
        const button = event.currentTarget;
        button.disabled = true;
        button.classList.add('is-busy');
        try { await action(); }
        catch (error) { alert(String(error?.message || error)); }
        finally { button.disabled = false; button.classList.remove('is-busy'); await render(); }
      }, className);
    }

    function showEntry(uid) {
      activeTab = 'notes';
      expandedUid = String(uid);
      panel.hidden = false;
      document.documentElement.classList.add('ma-panel-open');
      void render();
    }

    function close() {
      panel.hidden = true;
      document.documentElement.classList.remove('ma-panel-open');
    }

    return {
      refresh: () => { if (!panel.hidden) void render(); },
      refreshEntries: () => { if (!panel.hidden && activeTab === 'notes') void renderNotes(); },
      refreshStatus: () => { if (!panel.hidden && activeTab === 'run') render(); },
      showEntry,
      unmount: () => { close(); panel.remove(); launcher.remove(); },
    };
  }

  function el(tag, className = '', content = null) {
    const node = document.createElement(tag);
    if (className) node.className = className;
    if (Array.isArray(content)) {
      for (const child of content) if (child) node.append(child);
    } else if (content instanceof Node) {
      node.append(content);
    } else if (content != null) {
      node.textContent = String(content);
    }
    return node;
  }

  function btn(label, action, className = '') {
    const button = el('button', `ma-button ${className}`.trim(), label);
    button.type = 'button';
    button.addEventListener('click', action);
    return button;
  }

  function section(title, body = null) {
    const node = el('section', 'ma-section');
    if (title) node.append(el('h2', '', title));
    if (Array.isArray(body)) {
      for (const child of body) if (child) node.append(child);
    } else if (body) {
      node.append(body);
    }
    return node;
  }

  function grid(children) {
    return el('div', 'ma-action-grid', children);
  }

  function input(placeholder, value = '', type = 'text') {
    const node = document.createElement('input');
    node.className = 'ma-input'; node.type = type; node.placeholder = placeholder; node.value = value;
    return node;
  }

  function select(options, value = '') {
    const node = document.createElement('select');
    node.className = 'ma-select';
    for (const [id, label] of options) {
      const option = document.createElement('option'); option.value = id; option.textContent = label; option.selected = String(id) === String(value); node.append(option);
    }
    return node;
  }

  function span(text) { return el('span', '', text); }
  function splitKeywords(value) { return String(value || '').split(/[、,，]/u).map(item => item.trim()).filter(Boolean); }
  return Object.freeze({ mountUI });
})();

const __ma_module_4 = (() => {
  const { activatedUids, askModel, assistantExists, availableProfiles, boundWorldbook, clearHistory,
    context, ensureWorldbook, eventTypes, latestAssistant, loadHistory, messageIndex, onEvent,
    readWorldbook, replaceAssistant, saveHistory, saveSettings, saveWorldbook, settings,
    isPendingSwipe, } = __ma_module_0;
  const { applyFacts, applySummary, currentScene, deleteEntries, largeSummarySources, managedEntries,
    migrateOldEntries, overview, parseAudit, parseExtraction, parseImport, parseSummary, rollbackChanges,
    setCornerstone, setFocus, setFolder, setGameTime, setInsertionPosition, smallSummarySources,
    updateEntry, updateRecall, } = __ma_module_2;
  const { auditPrompt, extractionPrompt, importPrompt, revisionPrompt, summaryPrompt } = __ma_module_1;
  const { mountUI } = __ma_module_3;
  function startApplication() {
    const state = {
      busy: false,
      status: '等待处理',
      error: '',
      currentScene: '',
      activatedUids: [],
      undo: null,
      lastResult: null,
      cancelVersion: 0,
      bookCache: null,
    };

    let chain = Promise.resolve();
    let ui = null;
    let sequence = [];
    const unsubscribers = [];

    const api = {
      state: () => ({ ...state, settings: settings(), worldbookName: boundWorldbook() }),
      settings,
      saveSettings: patch => { const next = saveSettings(patch); ui?.refresh(); return next; },
      profiles: availableProfiles,
      listEntries,
      process,
      summarize,
      importText,
      updateEntry: (uid, content) => mutate('更新条目', (data) => updateEntry(data, uid, content)),
      updateRecall: (uid, value) => mutate('更新召回', data => updateRecall(data, uid, value)),
      setCornerstone: (uids, locked) => mutate(locked ? '设置基石' : '解除基石', data => setCornerstone(data, uids, locked)),
      setFocus: (uid, focused) => mutate(focused ? '设置焦点' : '解除焦点', data => setFocus(data, uid, focused)),
      setInsertionPosition: (uids, position) => mutate('修改定义位置', data => setInsertionPosition(data, uids, position)),
      setFolder: (uids, folder) => mutate('移动文件夹', data => setFolder(data, uids, folder)),
      deleteEntries: uids => mutate('删除条目', data => deleteEntries(data, uids)),
      setGameTime: value => mutate('设置游戏时间', data => setGameTime(data, value)),
      undo,
      cancel,
      testModel,
      migrate,
      reset,
      refresh: () => { invalidateBook(); ui?.refresh(); },
    };


    function queue(label, work) {
      const version = state.cancelVersion;
      const job = chain.then(async () => {
        if (version !== state.cancelVersion) return null;
        state.busy = true;
        state.status = label;
        state.error = '';
        ui?.refreshStatus();
        try {
          const result = await work(version);
          if (version === state.cancelVersion) state.status = '完成';
          state.lastResult = result || null;
          return result;
        } catch (error) {
          if (version === state.cancelVersion) {
            state.status = '失败';
            state.error = String(error?.message || error);
          }
          console.error('[Mirror Abyss]', error);
          throw error;
        } finally {
          state.busy = false;
          ui?.refreshStatus();
          ui?.refreshEntries();
        }
      });
      chain = job.catch(() => undefined);
      return job;
    }

    function cancel() {
      state.cancelVersion++;
      state.busy = false;
      state.status = '已取消';
      state.error = '';
      ui?.refreshStatus();
    }

    async function loadBook(force = false) {
      const name = boundWorldbook() || await ensureWorldbook();
      if (!force && state.bookCache?.name === name) return state.bookCache;
      const opened = await readWorldbook(name);
      state.bookCache = opened;
      return opened;
    }

    function invalidateBook() {
      state.bookCache = null;
    }

    async function saveBook(opened) {
      await saveWorldbook(opened.name, opened.data);
      state.bookCache = opened;
    }

    async function listEntries() {
      const opened = await loadBook();
      const entries = managedEntries(opened.data);
      return { name: opened.name, entries, overview: overview(entries) };
    }

    function process(mode = 'full', automatic = false, requestedIndex = -1) {
      return queue(automatic ? '自动整理正文' : '整理当前正文', async version => {
        let message = latestAssistant(requestedIndex);
        const cfg = settings();
        if (mode === 'audit' && !String(cfg.auditPrompt || '').trim()) throw new Error('请先在设置中填写审核提示词');

        if ((mode === 'audit' || (mode === 'full' && cfg.autoAudit)) && String(cfg.auditPrompt || '').trim()) {
          state.status = '审核正文'; ui?.refreshStatus();
          const audit = parseAudit(await askModel(auditPrompt(message.assistantText, cfg.auditPrompt)));
          if (!audit.passed) {
            state.status = '修正正文'; ui?.refreshStatus();
            const revised = await askModel(revisionPrompt(message.assistantText, audit.issues));
            if (version !== state.cancelVersion) return null;
            await replaceAssistant(message.index, revised);
            message = { ...message, assistantText: revised };
          }
          if (mode === 'audit') return { audited: true };
        }
        if (mode === 'audit') return { audited: true };

        state.status = '读取世界书'; ui?.refreshStatus();
        const opened = await loadBook();
        const beforeEntries = managedEntries(opened.data);
        const previousScene = state.currentScene || currentScene(beforeEntries);

        state.status = '模型提取'; ui?.refreshStatus();
        const raw = await askModel(extractionPrompt(message.playerText, message.assistantText, beforeEntries, previousScene));
        if (version !== state.cancelVersion) return null;
        const parsed = parseExtraction(raw, previousScene);

        const allChanges = [];
        const allTouched = [];

        if (automatic && cfg.autoSmallSummary && previousScene && parsed.scene && previousScene !== parsed.scene) {
          const summary = await automaticSummaries(opened, beforeEntries, previousScene, message.index, version);
          allChanges.push(...summary.changes);
          allTouched.push(...summary.touched);
        }

        const result = applyFacts(opened.data, parsed.groups, {
          automatic,
          messageIndex: message.index,
          scene: parsed.scene,
        });
        allChanges.push(...result.changes);
        allTouched.push(...result.touched);
        state.currentScene = parsed.scene || previousScene;

        if (allTouched.length) {
          state.status = '写入世界书'; ui?.refreshStatus();
          await saveBook(opened);
          await rememberMessageEffect(message.index, opened.name, mergeChanges(allChanges));
        }

        state.lastResult = { createdOrUpdated: [...new Set(allTouched)].length, uids: [...new Set(allTouched)] };
        return state.lastResult;
      });
    }

    async function automaticSummaries(opened, beforeEntries, scene, messageIndexValue, version) {
      const changes = [];
      const touched = [];
      const sources = smallSummarySources(beforeEntries, scene);
      if (sources.length < 2) return { changes, touched };

      state.status = `小总结 · ${scene}`; ui?.refreshStatus();
      const groups = parseSummary(await askModel(summaryPrompt('small', sources)), sources);
      if (version !== state.cancelVersion) return { changes, touched };
      const small = applySummary(opened.data, sources, groups, { automatic: true, kind: 'small', messageIndex: messageIndexValue });
      changes.push(...small.changes);
      touched.push(...small.touched);

      const cfg = settings();
      if (!cfg.autoLargeSummary) return { changes, touched };
      const entries = managedEntries(opened.data);
      const batches = new Set(entries.filter(entry => entry.summaryLevel === 'small').map(entry => entry.summaryBatch).filter(Boolean));
      if (batches.size < Number(cfg.largeSummaryGroups || 4)) return { changes, touched };
      const largeSources = largeSummarySources(entries, cfg.largeSummaryGroups);
      if (largeSources.length < 2) return { changes, touched };

      state.status = '大总结'; ui?.refreshStatus();
      const largeGroups = parseSummary(await askModel(summaryPrompt('large', largeSources)), largeSources);
      if (version !== state.cancelVersion) return { changes, touched };
      const large = applySummary(opened.data, largeSources, largeGroups, { automatic: true, kind: 'large', messageIndex: messageIndexValue });
      changes.push(...large.changes);
      touched.push(...large.touched);
      return { changes: mergeChanges(changes), touched: [...new Set(touched)] };
    }

    function summarize(kind = 'small', uids = [], requirement = '') {
      return queue(kind === 'large' ? '大总结' : kind === 'merge' ? '人工合并' : '小总结', async version => {
        const opened = await loadBook();
        const entries = managedEntries(opened.data);
        let sources = uids.length ? entries.filter(entry => uids.map(String).includes(String(entry.uid))) : [];
        if (!sources.length && kind === 'small') sources = smallSummarySources(entries, state.currentScene || currentScene(entries));
        if (!sources.length && kind === 'large') sources = largeSummarySources(entries, settings().largeSummaryGroups);
        if (sources.length < 2) throw new Error('至少需要两个条目');

        const mode = kind === 'merge' ? 'merge' : kind;
        const groups = parseSummary(await askModel(summaryPrompt(mode, sources, requirement)), sources);
        if (version !== state.cancelVersion) return null;
        const result = applySummary(opened.data, sources, groups, { automatic: false, kind: mode, messageIndex: latestAssistant().index });
        await saveBook(opened);
        state.undo = { label: kind === 'merge' ? '人工合并' : `${kind === 'large' ? '大' : '小'}总结`, worldbookName: opened.name, changes: result.changes };
        return result;
      });
    }

    function importText(text) {
      return queue('导入世界设定', async version => {
        const source = String(text || '').trim();
        if (!source) throw new Error('请先输入世界设定');
        const opened = await loadBook();
        const entries = managedEntries(opened.data);
        const groups = parseImport(await askModel(importPrompt(source, entries)));
        if (version !== state.cancelVersion) return null;
        const result = applyFacts(opened.data, groups, { automatic: false, messageIndex: -1, scene: '' });
        setCornerstone(opened.data, result.touched, true);
        await saveBook(opened);
        state.undo = { label: '导入世界设定', worldbookName: opened.name, changes: result.changes };
        return result;
      });
    }

    function mutate(label, mutator) {
      return queue(label, async () => {
        const opened = await loadBook();
        const result = mutator(opened.data) || { changes: [], touched: [] };
        if (result.touched?.length || result.changes?.length) await saveBook(opened);
        state.undo = result.changes?.length ? { label, worldbookName: opened.name, changes: result.changes } : null;
        return result;
      });
    }

    function undo() {
      const saved = state.undo;
      if (!saved) return Promise.resolve(null);
      return queue(`撤回 · ${saved.label}`, async () => {
        const opened = await loadBook(true);
        if (opened.name !== saved.worldbookName) throw new Error('当前世界书已经切换');
        rollbackChanges(opened.data, saved.changes);
        await saveBook(opened);
        state.undo = null;
        return true;
      });
    }

    function testModel() {
      return queue('测试模型', async () => {
        const text = await askModel({ system: '只输出：镜渊连接正常', user: '测试连接' });
        if (!text.includes('镜渊连接正常')) throw new Error(`模型返回：${text.slice(0, 80)}`);
        return text;
      });
    }

    function migrate() {
      return mutate('迁移旧条目', data => migrateOldEntries(data));
    }

    function reset() {
      return queue('重置镜渊条目', async () => {
        const opened = await loadBook();
        const entries = managedEntries(opened.data);
        for (const entry of entries) delete opened.data.entries[entry.uid];
        await saveBook(opened);
        await clearHistory();
        state.undo = null;
        state.currentScene = '';
        return { removed: entries.length };
      });
    }

    async function rememberMessageEffect(index, worldbookName, changes) {
      if (!changes?.length || index < 0) return;
      const history = loadHistory();
      const old = history.find(item => item.messageIndex === index && item.worldbookName === worldbookName);
      if (old) {
        const known = new Set(old.changes.map(change => String(change.uid)));
        for (const change of changes) if (!known.has(String(change.uid))) old.changes.push(change);
      } else {
        history.push({ messageIndex: index, worldbookName, changes });
      }
      await saveHistory(history);
    }

    async function rollbackMessage(index, reprocess, deleted = false) {
      return queue('撤回聊天操作', async () => {
        if (index < 0) return;
        const history = loadHistory();
        const current = history.filter(item => item.messageIndex === index);
        if (current.length) {
          const opened = await loadBook(true);
          let changed = false;
          for (const item of current) {
            if (item.worldbookName !== opened.name) continue;
            rollbackChanges(opened.data, item.changes);
            changed = true;
          }
          if (changed) await saveBook(opened);
        }

        let next = history.filter(item => item.messageIndex !== index);
        if (deleted) next = next.map(item => item.messageIndex > index ? { ...item, messageIndex: item.messageIndex - 1 } : item);
        if (current.length || deleted) await saveHistory(next);

        invalidateBook();
        if (reprocess && assistantExists(index)) setTimeout(() => { void process('full', true, index).catch(() => {}); }, 20);
      });
    }

    function subscribe() {
      const events = eventTypes();
      unsubscribers.push(
        onEvent(events.MESSAGE_RECEIVED, value => {
          sequence = messageTexts();
          if (settings().autoExtraction) void process('full', true, messageIndex(value)).catch(() => {});
        }),
        onEvent(events.MESSAGE_EDITED, value => {
          const index = messageIndex(value);
          sequence = messageTexts();
          void rollbackMessage(index, assistantExists(index)).catch(() => {});
        }),
        onEvent(events.MESSAGE_SWIPED, value => {
          const index = messageIndex(value);
          sequence = messageTexts();
          void rollbackMessage(index, !isPendingSwipe(index) && assistantExists(index)).catch(() => {});
        }),
        onEvent(events.MESSAGE_DELETED, () => {
          const next = messageTexts();
          const index = firstDifference(sequence, next);
          sequence = next;
          void rollbackMessage(index, false, true).catch(() => {});
        }),
        onEvent(events.CHAT_CHANGED, () => {
          cancel();
          invalidateBook();
          state.currentScene = '';
          state.activatedUids = [];
          state.undo = null;
          sequence = messageTexts();
          void inferScene().then(scene => { state.currentScene = scene; ui?.refresh(); });
        }),
        onEvent(events.GENERATION_STARTED, () => { state.activatedUids = []; ui?.refreshStatus(); }),
        onEvent(events.WORLD_INFO_ACTIVATED, entries => { state.activatedUids = activatedUids(entries); ui?.refreshStatus(); }),
        onEvent(events.WORLDINFO_UPDATED, name => {
          if (name && String(name) !== boundWorldbook()) return;
          invalidateBook();
          ui?.refreshEntries();
        }),
      );
    }

    async function inferScene() {
      try {
        if (!boundWorldbook()) return '';
        const opened = await loadBook();
        return currentScene(managedEntries(opened.data));
      } catch { return ''; }
    }

    function messageTexts() {
      return (context().chat || []).map(message => `${message?.is_user ? 'u' : 'a'}:${String(message?.mes || '')}`);
    }

    function firstDifference(left, right) {
      const length = Math.max(left.length, right.length);
      for (let i = 0; i < length; i++) if (left[i] !== right[i]) return i;
      return Math.max(0, right.length - 1);
    }

    function mergeChanges(changes) {
      const map = new Map();
      for (const change of changes) if (!map.has(String(change.uid))) map.set(String(change.uid), change);
      return [...map.values()];
    }

    // UI is unconditional: if this module runs, the window exists.
    ui = mountUI(api);
    ui.refresh();
    try { sequence = messageTexts(); } catch { sequence = []; }
    subscribe();
    void inferScene().then(scene => {
      state.currentScene = scene;
      ui?.refreshStatus();
    });

    return api;
  }
  return Object.freeze({ startApplication });
})();

const { startApplication } = __ma_module_4;

export { startApplication };

