// Generated by scripts/build.mjs. Edit src/, then run npm run build.

// Mirror Abyss build 4.0.78.

const __ma_module_0 = (() => {
  const ROOT_ID='mirror-abyss-core-control';
  const PANEL_ID='mirror-abyss-lite-panel';
  const POSITION_KEY='mirrorAbyssLite.launcherPosition.v1';
  const SIZE=44,MARGIN=8;

  function mountUI(api){
    document.getElementById(ROOT_ID)?.remove();
    document.getElementById(PANEL_ID)?.remove();

    let page='run',selected=new Set(),entries=[],worldbookName='',drag=null,suppressClick=false,openUid='';
    const root=document.createElement('div');root.id=ROOT_ID;root.className='ma-lite-floating-entry';
    const launcher=document.createElement('button');launcher.type='button';launcher.className='ma-lite-launcher';launcher.setAttribute('aria-label','打开镜渊面板');launcher.setAttribute('aria-expanded','false');launcher.title='Mirror Abyss｜镜渊';launcher.innerHTML='<i class="fa-solid fa-circle-nodes" aria-hidden="true"></i><span>镜渊</span>';
    launcher.addEventListener('click',event=>{event.preventDefault();event.stopPropagation();if(suppressClick){suppressClick=false;return;}togglePanel();});
    root.append(launcher);document.body.append(root);

    const panel=buildPanel();document.body.append(panel);
    applySavedPosition();bindDrag();

    function buildPanel(){
      const p=document.createElement('section');p.id=PANEL_ID;p.hidden=true;p.setAttribute('aria-label','镜渊操作面板');
      const header=document.createElement('div');header.className='ma-lite-header';
      const title=document.createElement('div');title.className='ma-lite-title';title.innerHTML='<strong>Mirror Abyss｜镜渊</strong><small>正文处理、世界书与维护</small>';
      const close=document.createElement('button');close.type='button';close.className='ma-lite-close';close.title='收起';close.innerHTML='<i class="fa-solid fa-xmark" aria-hidden="true"></i>';close.addEventListener('click',closePanel);
      header.append(title,close);
      const body=document.createElement('div');body.className='ma-lite-body';
      const nav=document.createElement('nav');nav.className='ma-lite-page-nav';nav.setAttribute('aria-label','镜渊面板分页');
      for(const [key,label] of [['run','运行'],['worldbook','世界书'],['settings','设置'],['maintenance','维护']]){const b=document.createElement('button');b.type='button';b.className='ma-lite-page-tab';b.dataset.page=key;b.textContent=label;b.addEventListener('click',()=>showPage(key));nav.append(b);}
      body.append(nav);
      for(const key of ['run','worldbook','settings','maintenance']){const node=document.createElement('section');node.className='ma-lite-page';node.dataset.page=key;node.hidden=key!==page;body.append(node);}
      p.append(header,body);showPage('run',false);return p;
    }

    function pageNode(key){return panel.querySelector(`.ma-lite-page[data-page="${key}"]`);}
    function showPage(key,refresh=true){page=key;for(const n of panel.querySelectorAll('.ma-lite-page'))n.hidden=n.dataset.page!==key;for(const b of panel.querySelectorAll('.ma-lite-page-tab'))b.setAttribute('aria-selected',b.dataset.page===key?'true':'false');if(refresh&&!panel.hidden)void refreshPage();}
    function togglePanel(){const opening=panel.hidden;panel.hidden=!opening;launcher.setAttribute('aria-expanded',opening?'true':'false');if(opening)void refreshPage();}
    function closePanel(){panel.hidden=true;launcher.setAttribute('aria-expanded','false');}
    async function refreshPage(){if(panel.hidden)return;if(page==='run')return renderRun();if(page==='worldbook')return refreshWorldbook();if(page==='settings')return renderSettings();renderMaintenance();}

    function renderRun(){
      const node=pageNode('run'),view=api.state();node.replaceChildren();
      const pipeline=document.createElement('section');pipeline.className='ma-lite-pipeline';
      const active=view.busy?'running':view.error?'error':view.status==='完成'?'success':'ready';
      for(const [kind,label] of [['audit','审核'],['revision','修正'],['extract','提取'],['write','写入']]){const card=document.createElement('div');card.className='ma-lite-stage';const head=document.createElement('div');head.className='ma-lite-stage-head';head.innerHTML=`<i class="ma-ind-dot" data-state="${active}"></i><span>${label}</span>`;const detail=document.createElement('div');detail.className='ma-lite-stage-detail';detail.textContent=view.busy?view.status:view.error?'失败':view.status||'待命';card.append(head,detail);pipeline.append(card);}
      const actions=document.createElement('div');actions.className='ma-lite-actions';actions.append(action('process','完整处理当前正文',()=>api.process('full')),action('audit','仅审核',()=>api.process('audit')),action('extract','仅提取',()=>api.process('extract')),action('cancel','取消当前任务',()=>api.cancel()));
      const status=document.createElement('div');status.className='ma-lite-status';status.dataset.error=view.error?'true':'false';status.textContent=view.error?`${view.status}｜${view.error}`:(view.status||'就绪');
      if(view.worldbookName)status.textContent+=`\n世界书：${view.worldbookName}`;
      node.append(pipeline,actions,status);
    }

    async function refreshWorldbook(){
      const node=pageNode('worldbook');
      try{const data=await api.listEntries();worldbookName=data.worldbookName||data.name||'';entries=data.entries||[];for(const uid of [...selected])if(!entries.some(x=>String(x.uid)===String(uid)))selected.delete(uid);renderWorldbook(node);}catch(error){node.replaceChildren(statusBox(`读取世界书失败：${error?.message||error}`,true));}
    }

    function renderWorldbook(node){
      node.replaceChildren();
      const quick=document.createElement('section');quick.className='ma-lite-worldbook-quick';const head=document.createElement('div');head.className='ma-lite-worldbook-quick-head';head.innerHTML='<strong>世界书控制</strong><small>整理操作只处理明确来源集合；提取仍走更新链。</small>';
      const qa=document.createElement('div');qa.className='ma-lite-worldbook-quick-actions';qa.append(action('smallSummary','运行小总结',()=>api.summarize('small',[...selected])),action('largeSummary','运行大总结',()=>api.summarize('large',[...selected])),action('merge','人工合并',()=>api.summarize('merge',[...selected])),action('testApiProbe','测试 API',()=>api.testModel()));
      const qstatus=document.createElement('div');qstatus.className='ma-lite-worldbook-quick-status';qstatus.textContent=worldbookName?`当前聊天世界书：${worldbookName}`:'当前聊天未绑定世界书';quick.append(head,qa,qstatus);node.append(quick);

      const management=document.createElement('section');management.className='ma-lite-management';const mh=document.createElement('div');mh.className='ma-lite-management-head';const mt=document.createElement('strong');mt.textContent='世界档案';const refresh=document.createElement('button');refresh.type='button';refresh.className='ma-lite-management-refresh';refresh.innerHTML='<i class="fa-solid fa-rotate" aria-hidden="true"></i>';refresh.title='重新读取当前聊天世界书';refresh.addEventListener('click',()=>void refreshWorldbook());mh.append(mt,refresh);
      const ms=document.createElement('div');ms.className='ma-lite-management-status';ms.textContent=`${entries.length} 条镜渊管理条目；展开、勾选、搜索只操作当前页面，不刷新世界书。`;
      const search=document.createElement('input');search.className='ma-lite-entry-search';search.placeholder='搜索标题、正文、关键词';
      const selectBar=document.createElement('div');selectBar.className='ma-lite-selection';const count=document.createElement('span');const selectionActions=document.createElement('div');selectionActions.className='ma-lite-selection-actions';selectionActions.append(simpleButton('全选',()=>{for(const e of visibleEntries(search.value))selected.add(String(e.uid));syncChecks();}),simpleButton('清空选择',()=>{selected.clear();syncChecks();}),simpleButton('移动文件夹',async()=>{const name=prompt('输入文件夹名称；留空回到默认分类');if(name!==null&&selected.size)await api.setFolder([...selected],name);}));selectBar.append(count,selectionActions);
      const list=document.createElement('div');list.className='ma-lite-entry-list';
      search.addEventListener('input',()=>paintEntries(list,search.value,count));management.append(mh,ms,search,selectBar,list);node.append(management);paintEntries(list,'',count);

      const importBox=document.createElement('section');importBox.className='ma-lite-world-setting';const ih=document.createElement('strong');ih.className='ma-lite-world-setting-head';ih.textContent='导入世界基础设定';const help=document.createElement('div');help.className='ma-lite-world-setting-help';help.textContent='文本交给当前核心整理后直接写入当前聊天绑定世界书。';const text=document.createElement('textarea');text.placeholder='粘贴世界设定';const ia=document.createElement('div');ia.className='ma-lite-world-setting-actions';ia.append(action('import','整理并导入',()=>api.importText(text.value)));importBox.append(ih,help,text,ia);node.append(importBox);
    }

    function visibleEntries(query){const q=String(query||'').trim().toLowerCase();return q?entries.filter(e=>`${e.title}\n${e.content}\n${e.keywords?.join(' ')}\n${e.secondaryKeywords?.join(' ')}`.toLowerCase().includes(q)):entries;}
    function paintEntries(list,query,count){list.replaceChildren();const visible=visibleEntries(query);if(!visible.length){const empty=document.createElement('div');empty.className='ma-lite-empty';empty.textContent='没有匹配条目';list.append(empty);}for(const entry of visible)list.append(entryRow(entry));count.textContent=`已选 ${selected.size} 条`;}
    function syncChecks(){for(const box of panel.querySelectorAll('.ma-lite-entry-check'))box.checked=selected.has(String(box.dataset.uid));const count=panel.querySelector('.ma-lite-selection>span');if(count)count.textContent=`已选 ${selected.size} 条`;}

    function entryRow(entry){
      const row=document.createElement('div');row.className='ma-lite-entry-row';row.dataset.uid=entry.uid;
      const head=document.createElement('div');head.className='ma-lite-entry-row-head';const check=document.createElement('input');check.type='checkbox';check.className='ma-lite-entry-check';check.dataset.uid=entry.uid;check.checked=selected.has(String(entry.uid));check.addEventListener('change',()=>{check.checked?selected.add(String(entry.uid)):selected.delete(String(entry.uid));syncChecks();});
      const title=document.createElement('div');title.className='ma-lite-entry-row-title';title.textContent=entry.title;title.title=entry.title;const open=document.createElement('button');open.type='button';open.className='ma-lite-entry-open';open.textContent=openUid===String(entry.uid)?'收起':'展开';open.addEventListener('click',()=>{if(openUid===String(entry.uid)){openUid='';row.querySelector('.ma-lite-entry-detail')?.remove();open.textContent='展开';return;}const old=panel.querySelector('.ma-lite-entry-detail');old?.remove();for(const b of panel.querySelectorAll('.ma-lite-entry-open'))b.textContent='展开';openUid=String(entry.uid);open.textContent='收起';row.append(entryDetail(entry));});head.append(check,title,open);
      const meta=document.createElement('div');meta.className='ma-lite-recall-meta';for(const [label,kind] of [[entry.type,'scene'],[entry.cornerstone?'基石':'','constant'],[entry.focus?'焦点':'','active'],[entry.constant?'常驻':'','bridge'],[entry.insertionPosition===0?'定义前':'定义后','history']])if(label){const badge=document.createElement('span');badge.className='ma-lite-badge';badge.dataset.kind=kind;badge.textContent=label;meta.append(badge);}row.append(head,meta);if(openUid===String(entry.uid))row.append(entryDetail(entry));return row;
    }

    function entryDetail(entry){
      const d=document.createElement('div');d.className='ma-lite-entry-detail';const editor=document.createElement('textarea');editor.className='ma-lite-entry-editor';editor.value=entry.content||'';
      const fields=document.createElement('div');fields.className='ma-lite-entry-fields';const keys=input(entry.keywords?.join('、')||'','主要关键词'),secondary=input(entry.secondaryKeywords?.join('、')||'','次关键词'),folder=input(entry.folder||'','文件夹');const position=document.createElement('select');position.className='ma-lite-entry-select';position.append(new Option('角色定义前','0'),new Option('角色定义后','1'));position.value=String(entry.insertionPosition===0?0:1);fields.append(keys,secondary,folder,position);
      const flags=document.createElement('div');flags.className='ma-lite-entry-flags';const constant=flag('常驻',entry.constant),cornerstone=flag('基石',entry.cornerstone),focus=entry.type==='人物'?flag('焦点',entry.focus):null;flags.append(constant.label,cornerstone.label);if(focus)flags.append(focus.label);
      const buttons=document.createElement('div');buttons.className='ma-lite-entry-buttons';buttons.append(simpleButton('保存',()=>api.saveEntry(entry.uid,{content:editor.value,keywords:split(keys.value),secondaryKeywords:split(secondary.value),folder:folder.value,constant:constant.input.checked,cornerstone:cornerstone.input.checked,focus:focus?.input.checked||false,position:Number(position.value)})),simpleButton('删除',async()=>{if(confirm(`删除 ${entry.title}？`))await api.deleteEntries([entry.uid]);},true));d.append(editor,fields,flags,buttons);return d;
    }

    function renderSettings(){
      const node=pageNode('settings'),cfg=api.settings();node.replaceChildren();
      const apiBox=document.createElement('section');apiBox.className='ma-lite-api';const ah=document.createElement('div');ah.className='ma-lite-api-head';ah.innerHTML='<i class="fa-solid fa-plug"></i><strong>镜渊处理 API</strong>';const select=document.createElement('select');select.className='ma-lite-api-select';select.append(new Option('当前 SillyTavern 连接',''));for(const p of api.profiles())select.append(new Option(p.name,p.id));select.value=cfg.modelProfileId||'';select.addEventListener('change',()=>api.saveSettings({modelProfileId:select.value}));const as=document.createElement('div');as.className='ma-lite-api-status';as.textContent=cfg.modelProfileId?'使用指定 Connection Profile':'跟随当前 SillyTavern 连接';apiBox.append(ah,select,as);node.append(apiBox);
      const switches=document.createElement('div');switches.className='ma-lite-switches';switches.append(settingSwitch('自动审核',cfg.autoAudit,v=>api.saveSettings({autoAudit:v})),settingSwitch('自动提取',cfg.autoExtraction,v=>api.saveSettings({autoExtraction:v})),settingSwitch('自动小总结',cfg.autoSmallSummary,v=>api.saveSettings({autoSmallSummary:v})));node.append(wrap('自动化与功能开关',switches,true));
      const rules=document.createElement('section');rules.className='ma-lite-prompt-editor';const rt=document.createElement('strong');rt.textContent='基础审核提示词';const prompt=document.createElement('textarea');prompt.value=cfg.auditPrompt||'';const save=simpleButton('保存审核提示词',()=>api.saveSettings({auditPrompt:prompt.value}));save.classList.add('ma-lite-prompt-save');const tokens=input(String(cfg.responseTokens||8192),'最大输出 Tokens','number');tokens.addEventListener('change',()=>api.saveSettings({responseTokens:Number(tokens.value)||8192}));rules.append(rt,prompt,tokens,save);node.append(wrap('审核与输出',rules,false));
    }

    function renderMaintenance(){
      const node=pageNode('maintenance'),view=api.state();node.replaceChildren();const reset=document.createElement('section');reset.className='ma-lite-reset';const h=document.createElement('strong');h.className='ma-lite-reset-head';h.textContent='维护';const help=document.createElement('div');help.className='ma-lite-reset-help';help.textContent='撤回恢复上一次手动写入；清空只删除当前世界书中的镜渊管理条目。';const actions=document.createElement('div');actions.className='ma-lite-reset-actions';actions.append(simpleButton(view.undo?`撤回：${view.undo.label}`:'没有可撤回操作',async()=>{if(view.undo)await api.undo();}),simpleButton('清空镜渊管理条目',async()=>{if(confirm('确定清空当前世界书中的镜渊管理条目？'))await api.reset();},true));reset.append(h,help,actions);node.append(reset);
    }

    function action(kind,label,fn){const b=document.createElement('button');b.type='button';b.className='ma-lite-action';b.dataset.kind=kind;b.textContent=label;b.addEventListener('click',()=>void runAction(b,fn));return b;}
    async function runAction(button,fn){if(button.disabled)return;button.disabled=true;try{await fn();if(page==='worldbook')await refreshWorldbook();else if(page==='run')renderRun();else if(page==='maintenance')renderMaintenance();}catch(error){api.showError?.(error,api.raw?.()||error?.raw||'');if(!api.showError)alert(`${error?.message||error}`);}finally{button.disabled=false;}}
    function simpleButton(label,fn,danger=false){const b=document.createElement('button');b.type='button';b.className='ma-lite-entry-button';if(danger)b.dataset.danger='true';b.textContent=label;b.addEventListener('click',()=>void runAction(b,fn));return b;}
    function statusBox(text,error=false){const n=document.createElement('div');n.className='ma-lite-status';n.dataset.error=error?'true':'false';n.textContent=text;return n;}
    function input(value,placeholder,type='text'){const n=document.createElement('input');n.className='ma-lite-entry-input';n.value=value;n.placeholder=placeholder;n.type=type;return n;}
    function flag(text,checked){const label=document.createElement('label'),input=document.createElement('input');input.type='checkbox';input.checked=checked;label.append(input,document.createTextNode(text));return{label,input};}
    function split(value){return String(value||'').split(/[、,，]/u).map(x=>x.trim()).filter(Boolean);}
    function settingSwitch(text,checked,fn){const label=document.createElement('label');label.className='ma-lite-switch';const input=document.createElement('input');input.type='checkbox';input.checked=!!checked;const box=document.createElement('span');box.className='ma-lite-switch-text';const b=document.createElement('b');b.textContent=text;box.append(b);label.append(input,box);input.addEventListener('change',()=>fn(input.checked));return label;}
    function wrap(title,content,open=false){const details=document.createElement('details');details.className='ma-lite-tool-group';details.open=open;const summary=document.createElement('summary');summary.textContent=title;const body=document.createElement('div');body.className='ma-lite-tool-content';body.append(content);details.append(summary,body);return details;}

    function applySavedPosition(){try{const saved=JSON.parse(localStorage.getItem(POSITION_KEY)||'null');if(!saved||!Number.isFinite(saved.xRatio)||!Number.isFinite(saved.yRatio))return;const maxLeft=Math.max(MARGIN,innerWidth-SIZE-MARGIN),maxTop=Math.max(MARGIN,innerHeight-SIZE-MARGIN);setPosition(MARGIN+clamp(saved.xRatio)*Math.max(0,maxLeft-MARGIN),MARGIN+clamp(saved.yRatio)*Math.max(0,maxTop-MARGIN),false);}catch{}}
    function bindDrag(){
      const down=event=>{if(event.pointerType==='mouse'&&event.button!==0)return;event.stopPropagation();const r=root.getBoundingClientRect();drag={pointerId:event.pointerId,startX:event.clientX,startY:event.clientY,left:r.left,top:r.top,moved:false};try{launcher.setPointerCapture?.(event.pointerId);}catch{}};
      const move=event=>{if(!drag||drag.pointerId!==event.pointerId)return;const dx=event.clientX-drag.startX,dy=event.clientY-drag.startY;if(!drag.moved&&Math.hypot(dx,dy)<6)return;drag.moved=true;event.preventDefault();event.stopPropagation();root.classList.add('is-dragging');setPosition(drag.left+dx,drag.top+dy,false);};
      const finish=event=>{if(!drag||drag.pointerId!==event.pointerId)return;if(drag.moved)event.preventDefault();event.stopPropagation();try{launcher.releasePointerCapture?.(event.pointerId);}catch{}root.classList.remove('is-dragging');if(drag.moved){suppressClick=true;setTimeout(()=>{suppressClick=false;},500);persistPosition();}drag=null;};
      const resize=()=>{if(!root||drag)return;const r=root.getBoundingClientRect();if(root.style.left)setPosition(r.left,r.top,true);};
      launcher.addEventListener('pointerdown',down);launcher.addEventListener('pointermove',move);launcher.addEventListener('pointerup',finish);launcher.addEventListener('pointercancel',finish);window.addEventListener('resize',resize,{passive:true});
    }
    function setPosition(left,top,persist=false){const maxLeft=Math.max(MARGIN,innerWidth-SIZE-MARGIN),maxTop=Math.max(MARGIN,innerHeight-SIZE-MARGIN);const x=Math.min(maxLeft,Math.max(MARGIN,Number(left)||MARGIN)),y=Math.min(maxTop,Math.max(MARGIN,Number(top)||MARGIN));root.style.left=`${Math.round(x)}px`;root.style.top=`${Math.round(y)}px`;root.style.right='auto';root.style.bottom='auto';root.style.transform='none';if(persist)persistPosition();}
    function persistPosition(){try{const r=root.getBoundingClientRect(),h=Math.max(1,innerWidth-SIZE-MARGIN*2),v=Math.max(1,innerHeight-SIZE-MARGIN*2);localStorage.setItem(POSITION_KEY,JSON.stringify({xRatio:clamp((r.left-MARGIN)/h),yRatio:clamp((r.top-MARGIN)/v)}));}catch{}}
    function clamp(v){return Math.max(0,Math.min(1,Number(v)||0));}

    return{refresh:()=>{if(!panel.hidden)void refreshPage();},refreshEntries:()=>{if(!panel.hidden&&page==='worldbook')void refreshWorldbook();},refreshStatus:()=>{if(!panel.hidden&&page==='run')renderRun();},showEntry:uid=>{openUid=String(uid);page='worldbook';panel.hidden=false;launcher.setAttribute('aria-expanded','true');showPage('worldbook');},showError:(error,raw='')=>alert(`${String(error?.message||error)}${raw?`\n\nAI 原始文本：\n${raw}`:''}`),unmount:()=>{panel.remove();root.remove();}};
  }
  return Object.freeze({ mountUI });
})();

const __ma_module_1 = (() => {
  const { mountUI } = __ma_module_0;
  const KEY='mirrorAbyssClean';
  const TYPES=['人物','场景','物品','事件','世界','基础设定'];
  const DEF={autoAudit:false,autoExtraction:true,autoSmallSummary:true,responseTokens:8192,modelProfileId:'',auditPrompt:''};
  const 格式=/\[([^\[\]]+)\]|【([^【】]+)】|（([^（）]+)）|［([^［］]+)］|\(([^()]+)\)/gu;
  const 现=ctx=>globalThis.SillyTavern?.getContext?.()||ctx;

  async function 读(ctx,name=''){
    ctx=现(ctx);name||=String(ctx.chatMetadata?.world_info||'').trim();
    return{name,book:name?await ctx.loadWorldInfo(name)||{entries:{}}:{entries:{}}};
  }

  async function 问(ctx,cfg,规则,内容){
    ctx=现(ctx);const 消息=[{role:'system',content:规则},{role:'user',content:内容}];
    const 回答=cfg.modelProfileId
      ?await ctx.ConnectionManagerRequestService.sendRequest(cfg.modelProfileId,消息,cfg.responseTokens,{stream:false,extractData:true,includePreset:false,includeInstruct:false},{})
      :await ctx.generateRaw({systemPrompt:规则,prompt:内容,responseLength:cfg.responseTokens,trimNames:false});
    问.原文=String(回答?.content??回答??'').trim();return 问.原文;
  }

  function 拆(文本){
    const 结果=[];
    for(const 行 of 文本.replace(/```/g,'').split(/\r?\n/)){
      const 值=[];for(const m of 行.matchAll(格式))值.push(String(m[1]??m[2]??m[3]??m[4]??m[5]??'').trim());
      if(值.length>=5&&TYPES.includes(值[0]))结果.push([值[0],值[1],值[2],值[3],值.slice(4).join('')]);
    }
    if(!结果.length){const e=new Error('AI返回格式无法识别');e.raw=文本;throw e;}return 结果;
  }

  async function 存(ctx,数据){
    ctx=现(ctx);ctx.chatMetadata||={};
    if(!数据.name){数据.name=`镜渊-${ctx.getCurrentChatId?.()||'世界书'}`;ctx.chatMetadata.world_info=数据.name;await ctx.saveMetadata?.();}
    await ctx.saveWorldInfo(数据.name,数据.book,true);
  }

  function 写(书,结果,来源=[],附加={}){
    const 改动=[],组={};
    for(const[类型,名称,关键词,栏目,事实]of 结果){const 标题=`${类型}｜${名称}`;组[标题]||={名称,关键词:关键词.split(/[、,，]/).filter(Boolean),栏目:{}};(组[标题].栏目[栏目]||=[]).push(事实);}
    for(const uid of 来源){if(!书.entries[uid])continue;改动.push({uid:String(uid),before:structuredClone(书.entries[uid])});delete 书.entries[uid];}
    for(const 标题 in 组){
      const g=组[标题];let 条目=来源.length?null:Object.values(书.entries).find(x=>x.comment===标题),before=条目?structuredClone(条目):null;
      if(!条目){let uid=0;while(书.entries[uid])uid++;条目=书.entries[uid]={uid,key:[],keysecondary:[],comment:'',content:'',constant:false,position:1,disable:false,extensions:{}};}
      条目.comment=标题;条目.key=[...new Set([g.名称,标题,...g.关键词])];条目.content=Object.entries(g.栏目).map(([k,v])=>`【${k}】\n- ${v.join('\n- ')}`).join('\n\n');
      条目.extensions||={};条目.extensions.mirrorAbyss={...(条目.extensions.mirrorAbyss||{}),managed:true,updatedAt:Date.now(),...附加};改动.push({uid:String(条目.uid),before});
    }
    return 改动;
  }

  async function 总结(ctx,cfg,种类,ids){
    const 数据=await 读(ctx);if(!ids.length)ids=Object.keys(数据.book.entries).filter(x=>数据.book.entries[x]?.extensions?.mirrorAbyss?.managed===true);ids=ids.filter(x=>数据.book.entries[x]);
    if(种类==='merge'&&ids.length<2)throw new Error('请至少选择两个条目');
    const 来源=ids.map(x=>`${数据.book.entries[x].comment}\n${数据.book.entries[x].content}`).join('\n\n');
    const 规则=种类==='merge'?'把这些来源整理成更少的最终条目。只返回最终结果。每行：[类型][名称][关键词][栏目][事实]':'把这些来源整理成最终条目。只返回最终结果。每行：[类型][名称][关键词][栏目][事实]';
    const 改动=写(数据.book,拆(await 问(ctx,cfg,规则,来源)),ids,{summaryLevel:种类,summaryBatch:Date.now()});await 存(ctx,数据);return{name:数据.name,changes:改动};
  }

  async function startApplication(ctx){
    const first=现(ctx),cfg={...DEF,...(first.extensionSettings?.[KEY]||{})};
    let undo=null,cancel=0,scene='',busy=false,status='等待处理',error='',ui=null,lastResult=null,activatedUids=[];

    async function 同步场景(){
      const 数据=await 读(ctx);let latest=null;
      for(const e of Object.values(数据.book.entries)){const x=e?.extensions?.mirrorAbyss;if(x?.managed===true&&x.scene&&(!latest||Number(x.updatedAt||0)>Number(latest.updatedAt||0)))latest=x;}
      scene=String(latest?.scene||'');
    }

    async function 正文(mode,index=-1){
      const c=现(ctx);if(index<0){index=c.chat.length-1;while(index>=0&&(c.chat[index]?.is_user||c.chat[index]?.is_system))index--;}
      const m=c.chat[index];if(!m)return{uids:[]};
      let text=String(m.mes||''),player='';for(let i=index-1;i>=0;i--)if(c.chat[i]?.is_user){player=String(c.chat[i].mes||'');break;}
      if(mode!=='extract'&&cfg.auditPrompt){const r=await 问(c,cfg,`${cfg.auditPrompt}\n通过只输出[通过]，否则输出修正后的完整正文。`,text);if(!r.includes('[通过]')){text=r;m.mes=r;await c.saveChat?.();}}
      if(mode==='audit')return{uids:[]};
      const 数据=await 读(c),known=[];for(const uid in 数据.book.entries){const e0=数据.book.entries[uid];if(e0?.extensions?.mirrorAbyss?.managed===true)known.push(`${e0.comment}\n${e0.content}`);}
      const token=++cancel,r=await 问(c,cfg,`只提取已经发生的事实。每行：[类型][名称][关键词][栏目][事实]。类型：${TYPES.join('、')}。没有变化输出无。`,`已有：\n${known.join('\n')||'无'}\n玩家：${player}\nAI：${text}`);if(token!==cancel||r==='无')return{uids:[]};
      const rows=拆(r),next=rows.find(x=>x[0]==='场景')?.[1]||scene,old=scene,oldIds=old&&next!==old?Object.keys(数据.book.entries).filter(uid=>数据.book.entries[uid]?.extensions?.mirrorAbyss?.scene===old):[];
      const changes=写(数据.book,rows,[],{scene:next});await 存(c,数据);scene=next;
      const touched=new Set(changes.map(x=>x.uid)),summaryIds=oldIds.filter(uid=>!touched.has(String(uid)));
      let more=[],summaryError=null;if(cfg.autoSmallSummary&&summaryIds.length)try{more=(await 总结(c,cfg,'small',summaryIds)).changes;}catch(e){summaryError=e;}
      c.chatMetadata||={};c.chatMetadata[KEY]||={};c.chatMetadata[KEY].history||=[];c.chatMetadata[KEY].history.push({messageIndex:index,worldbookName:数据.name,changes:[...changes,...more]});await c.saveMetadata?.();
      if(summaryError)throw summaryError;return{uids:[...new Set([...changes,...more].map(x=>String(x.uid)))]};
    }

    async function 改条目(ids,fn,label){
      const 数据=await 读(ctx),changes=[];for(const uid of ids){const e=数据.book.entries[uid];if(!e)continue;changes.push({uid:String(uid),before:structuredClone(e)});fn(e,数据.book,uid);}
      if(changes.length){await 存(ctx,数据);undo={name:数据.name,changes,label};lastResult={uids:changes.map(x=>x.uid)};}return changes;
    }

    const api={
      state(){const c=现(ctx),worldbookName=String(c.chatMetadata?.world_info||'').trim();return{scene,currentScene:scene,worldbook:worldbookName,worldbookName,busy,status,error,undo:undo?{label:undo.label||'上次操作'}:null,lastResult,activatedUids:[...activatedUids]};},
      raw:()=>问.原文||'',
      settings:()=>({...cfg}),
      saveSettings(patch){const c=现(ctx);Object.assign(cfg,patch);c.extensionSettings||={};c.extensionSettings[KEY]={...cfg};c.saveSettingsDebounced?.();},
      profiles(){const s=现(ctx).ConnectionManagerRequestService;if(!s?.getSupportedProfiles)return[];try{return(s.getSupportedProfiles()||[]).map(x=>({id:String(x.id),name:String(x.name||x.id)}));}catch{return[];}},
      async listEntries(){
        const 数据=await 读(ctx),entries=[];
        for(const uid in 数据.book.entries){const e=数据.book.entries[uid],x=e?.extensions?.mirrorAbyss;if(x?.managed!==true)continue;const[type,...rest]=String(e.comment||'').split('｜');entries.push({uid:String(uid),type:type||'条目',name:rest.join('｜')||String(e.comment||uid),title:String(e.comment||uid),content:String(e.content||''),keywords:[...(e.key||[])],secondaryKeywords:[...(e.keysecondary||[])],folder:String(x.folder||''),cornerstone:!!x.cornerstone,focus:!!x.focus,summaryLevel:String(x.summaryLevel||''),constant:!!e.constant,position:Number(e.position||0),insertionPosition:Number(e.position||0)});}
        return{name:数据.name,worldbookName:数据.name,entries};
      },
      async process(mode='full'){
        if(busy)return;busy=true;status=mode==='audit'?'审核正文':mode==='extract'?'提取世界事实':'整理当前正文';error='';
        try{lastResult=await 正文(mode);return lastResult;}catch(e){error=String(e?.message||e);throw e;}finally{busy=false;status=error?'失败':'完成';}
      },
      async summarize(kind,ids=[]){
        if(busy)return;busy=true;status=kind==='merge'?'人工合并':kind==='large'?'大总结':'小总结';error='';
        try{undo=await 总结(ctx,cfg,kind,ids);undo.label=status;lastResult={uids:[...new Set(undo.changes.map(x=>String(x.uid)))]};return undo;}catch(e){error=String(e?.message||e);throw e;}finally{busy=false;status=error?'失败':'完成';}
      },
      async importText(text){const source=String(text||'').trim();if(!source)throw new Error('请先输入世界设定');const 数据=await 读(ctx),changes=写(数据.book,拆(await 问(ctx,cfg,`整理成事实。每行：[类型][名称][关键词][栏目][事实]。类型：${TYPES.join('、')}`,source)),[],{cornerstone:true});await 存(ctx,数据);undo={name:数据.name,changes,label:'导入'};lastResult={uids:changes.map(x=>x.uid)};},
      updateEntry:(uid,content)=>改条目([uid],e=>{e.content=String(content||'');e.extensions.mirrorAbyss.updatedAt=Date.now();},'更新条目'),
      updateRecall:(uid,value)=>改条目([uid],e=>{e.key=[...(value.keywords||[])];e.keysecondary=[...(value.secondaryKeywords||[])];e.constant=!!value.constant;e.extensions.mirrorAbyss.updatedAt=Date.now();},'更新召回'),
      setCornerstone:(ids,value)=>改条目(ids,e=>{e.extensions.mirrorAbyss.cornerstone=!!value;},value?'设置基石':'解除基石'),
      setInsertionPosition:(ids,value)=>改条目(ids,e=>{e.position=Number(value);},'修改定义位置'),
      setFolder:(ids,value)=>改条目(ids,e=>{e.extensions.mirrorAbyss.folder=String(value||'');},'移动文件夹'),
      deleteEntries:(ids)=>改条目(ids,(e,book,uid)=>{delete book.entries[uid];},'删除条目'),
      async setFocus(uid,value){
        const 数据=await 读(ctx),changes=[],e=数据.book.entries[uid];if(!e)return;if(value)for(const k in 数据.book.entries){const x=数据.book.entries[k]?.extensions?.mirrorAbyss;if(String(k)!==String(uid)&&x?.managed===true&&x.focus){changes.push({uid:String(k),before:structuredClone(数据.book.entries[k])});x.focus=false;}}
        changes.push({uid:String(uid),before:structuredClone(e)});e.extensions.mirrorAbyss.focus=!!value;e.extensions.mirrorAbyss.updatedAt=Date.now();await 存(ctx,数据);undo={name:数据.name,changes,label:value?'设置焦点':'解除焦点'};lastResult={uids:changes.map(x=>x.uid)};
      },
      async saveEntry(uid,value){const 数据=await 读(ctx),e=数据.book.entries[uid];if(!e)return;const changes=[{uid:String(uid),before:structuredClone(e)}],x=e.extensions?.mirrorAbyss||{};e.content=String(value.content||'');e.key=[...(value.keywords||[])];e.keysecondary=[...(value.secondaryKeywords||[])];e.constant=!!value.constant;e.position=Number(value.position||0);e.extensions||={};e.extensions.mirrorAbyss={...x,folder:String(value.folder||''),cornerstone:!!value.cornerstone,focus:!!value.focus,managed:true,updatedAt:Date.now()};await 存(ctx,数据);undo={name:数据.name,changes,label:'保存条目'};lastResult={uids:[String(uid)]};},
      cornerstone(ids,value){return api.setCornerstone(ids,value);},position(ids,value){return api.setInsertionPosition(ids,value);},folder(ids,value){return api.setFolder(ids,value);},remove(ids){return api.deleteEntries(ids);},
      async undo(){if(!undo)return;const 数据=await 读(ctx,undo.name);for(let i=undo.changes.length-1;i>=0;i--){const x=undo.changes[i];if(x.before==null)delete 数据.book.entries[x.uid];else 数据.book.entries[x.uid]=structuredClone(x.before);}await 存(ctx,数据);undo=null;lastResult=null;},
      cancel(){cancel++;busy=false;status='已取消';error='';},
      testModel:()=>问(ctx,cfg,'只输出：镜渊连接正常','测试'),
      test:()=>问(ctx,cfg,'只输出：镜渊连接正常','测试'),
      async reset(){const c=现(ctx),数据=await 读(c);for(const uid in 数据.book.entries)if(数据.book.entries[uid]?.extensions?.mirrorAbyss?.managed===true)delete 数据.book.entries[uid];if(数据.name)await 存(c,数据);if(c.chatMetadata?.[KEY])delete c.chatMetadata[KEY];await c.saveMetadata?.();undo=null;scene='';lastResult=null;},
    };

    try{await 同步场景();}catch{}ui=mountUI(api);

    const events=first.eventTypes||{},source=first.eventSource;
    source?.on?.(events.MESSAGE_RECEIVED,()=>{if(cfg.autoExtraction&&!busy)api.process(cfg.autoAudit?'full':'extract').then(()=>{ui?.refreshStatus?.();ui?.refreshEntries?.();}).catch(e=>ui?.showError?.(e,问.原文||''));});
    source?.on?.(events.CHAT_CHANGED,async()=>{cancel++;undo=null;scene='';lastResult=null;activatedUids=[];await 同步场景();ui?.refresh?.();});
    source?.on?.(events.WORLD_INFO_ACTIVATED,entries=>{activatedUids=(entries||[]).map(x=>String(x?.uid??x)).filter(Boolean);ui?.refreshStatus?.();});
    for(const type of ['MESSAGE_EDITED','MESSAGE_SWIPED','MESSAGE_DELETED'])source?.on?.(events[type],async value=>{
      const c=现(ctx);cancel++;const index=Number(value?.messageId??value?.index??value??-1),history=c.chatMetadata?.[KEY]?.history||[],receipt=history.find(x=>x.messageIndex===index);if(!receipt)return;
      const 数据=await 读(c,receipt.worldbookName);for(let i=receipt.changes.length-1;i>=0;i--){const x=receipt.changes[i];if(x.before==null)delete 数据.book.entries[x.uid];else 数据.book.entries[x.uid]=structuredClone(x.before);}await 存(c,数据);history.splice(history.indexOf(receipt),1);
      if(type==='MESSAGE_DELETED')for(const h of history)if(h.messageIndex>index)h.messageIndex--;await c.saveMetadata?.();if(type!=='MESSAGE_DELETED')await api.process(cfg.autoAudit?'full':'extract');ui?.refresh?.();
    });
  }
  return Object.freeze({ startApplication });
})();

const { startApplication } = __ma_module_1;

export { startApplication };

