// Generated by scripts/build.mjs. Edit src/, then run npm run build.

// Mirror Abyss build 4.0.54.

const __ma_module_0 = (() => {
  const TYPE_ICON = { 人物: '人', 场景: '景', 物品: '物', 事件: '事', 世界: '界', 基础设定: '基' };

  function mountUI(api) {
    let activeTab = 'run';
    let expandedUid = '';
    let search = '';
    let folder = '';
    const selected = new Set();

    const root = document.body || document.documentElement;

    const launcher = el('button', 'ma-launcher', '镜');
    launcher.type = 'button';
    launcher.title = '镜渊 · 世界记忆';
    // Fallback layout: the launcher stays visible even if the stylesheet fails.
    launcher.style.cssText = 'position:fixed;right:14px;bottom:82px;z-index:2147483000;width:52px;height:52px;border-radius:18px;border:1px solid rgba(0,0,0,.12);background:rgba(255,255,255,.88);color:#222;font-size:18px;font-weight:700;';
    root.append(launcher);

    // Keep the proven old-style window skeleton: header / tabs / content.
    // The game feeling comes from CSS only, so the DOM stays boring and reliable.
    const panel = el('section', 'ma-root ma-panel');
    panel.hidden = false;
    panel.innerHTML = `
      <div class="ma-window">
        <div class="ma-atmosphere" aria-hidden="true">
          <i></i><i></i><i></i>
        </div>
        <header class="ma-header">
          <div class="ma-brand">
            <span class="ma-brand-mark">镜</span>
            <span class="ma-brand-copy">
              <strong>镜渊</strong>
              <small>世界记忆</small>
            </span>
          </div>
          <button type="button" class="ma-close" data-close aria-label="关闭">×</button>
        </header>
        <nav class="ma-tabs" aria-label="镜渊功能"></nav>
        <main class="ma-main"></main>
      </div>`;
    root.append(panel);

    const tabs = panel.querySelector('.ma-tabs');
    const main = panel.querySelector('.ma-main');
    const tabNames = [['run', '旅程'], ['notes', '档案'], ['import', '设定'], ['settings', '选项']];
    for (const [id, label] of tabNames) {
      const button = btn(label, () => { activeTab = id; render(); });
      button.dataset.tab = id;
      tabs.append(button);
    }

    launcher.addEventListener('click', () => {
      panel.hidden = false;
      document.documentElement.classList.add('ma-panel-open');
      render();
    });
    panel.querySelector('[data-close]').addEventListener('click', () => {
      panel.hidden = true;
      document.documentElement.classList.remove('ma-panel-open');
    });

    async function render(entries = null, suppliedView = null) {
      if (panel.hidden) return;
      for (const button of tabs.querySelectorAll('[data-tab]')) button.classList.toggle('is-active', button.dataset.tab === activeTab);
      main.replaceChildren();
      if (activeTab === 'run') renderRun(suppliedView);
      if (activeTab === 'notes') await renderNotes(entries);
      if (activeTab === 'import') {
        const text = document.createElement('textarea');
        text.className = 'ma-input ma-import-text';
        text.placeholder = '粘贴世界设定，或把 TXT 内容复制到这里';
        main.append(section('写入世界', [
          el('p', 'ma-page-intro', '把世界设定交给模型整理，然后直接写进当前世界书。'),
          text,
          el('p', 'ma-help', '导入后的条目自动设为基石。'),
          taskButton('整理并导入', () => api.runAction('import', { text: text.value })),
        ]));
      }
      if (activeTab === 'settings') renderSettings();
    }

    function renderRun(suppliedView = null) {
      const view = suppliedView || api.state();
      const hero = el('section', 'ma-story-hero', [
        el('h1', 'ma-scene-title', view.currentScene || '等待故事继续'),
        el('div', 'ma-story-rule'),
        el('small', 'ma-worldbook-name', `世界书 · ${view.worldbookName || '未绑定'}`),
      ]);
      const choices = section('选择', el('div', 'ma-choice-list', [
        taskButton('整理当前正文', () => api.runFull('full'), 'ma-choice'),
        taskButton('仅提取世界事实', () => api.runFull('extract'), 'ma-choice'),
        taskButton('审核当前正文', () => api.runFull('audit'), 'ma-choice ma-choice-secondary'),
        taskButton('结算当前场景', () => api.runSummary('small'), 'ma-choice ma-choice-secondary'),
        taskButton('整理长期记忆', () => api.runSummary('large'), 'ma-choice ma-choice-secondary'),
        view.busy ? btn('中止当前任务', () => api.cancel(), 'ma-choice ma-danger') : null,
      ]));
      const status = section('运行记录');
      const text = view.error ? `${view.status} · ${view.error}` : view.status;
      status.append(el('div', `ma-status${view.error ? ' is-error' : ''}`, text));
      if (view.busy) status.append(el('small', 'ma-help', '任务正在运行'));
      if (view.undo) status.append(el('div', 'ma-inline-actions', [el('span', '', `可撤回：${view.undo.label}`), taskButton('撤回', () => api.runRollback(), 'ma-mini ma-quiet')]));
      if (view.activatedUids?.length) {
        const activated = el('div', 'ma-activated-row', el('strong', '', '本轮实际激活'));
        for (const uid of view.activatedUids) {
          activated.append(btn(`UID ${uid}`, () => {
            activeTab = 'notes';
            expandedUid = String(uid);
            panel.hidden = false;
            document.documentElement.classList.add('ma-panel-open');
            void render();
          }, 'ma-mini ma-quiet'));
        }
        status.append(activated);
      }
      if (view.lastUids?.length) status.append(el('small', 'ma-help', `本次更新：${view.lastUids.join('、')}`));
      main.append(hero, choices, status);
    }

    async function renderNotes(entries = null) {
      if (!entries) main.replaceChildren(section('世界档案', el('div', 'ma-empty', '读取中…')));
      try {
        entries ||= await api.listEntries();
        if (activeTab !== 'notes') return;
        main.replaceChildren();
        const folders = [];
        const folderNames = new Set();
        const grouped = new Map();
        let filteredCount = 0;
        const query = search.toLowerCase();
        for (const entry of entries) {
          if (entry.folder && !folderNames.has(entry.folder)) { folderNames.add(entry.folder); folders.push(entry.folder); }
          if ((query && !`${entry.title}\n${entry.content}`.toLowerCase().includes(query)) || (folder && entry.folder !== folder)) continue;
          const key = entry.folder || '默认分类';
          if (!grouped.has(key)) grouped.set(key, []);
          grouped.get(key).push(entry);
          filteredCount++;
        }

        const toolbar = el('section', 'ma-archive-toolbar');
        toolbar.append(el('div', 'ma-archive-title', [el('h1', '', '世界档案'), el('span', 'ma-folder-count', `${entries.length} 条记录`)]));
        const searchInput = input('搜索名称/正文', search);
        searchInput.addEventListener('input', () => { search = searchInput.value; void renderNotes(entries); });
        const folderOptions = [['', '全部文件夹']];
        for (const name of folders) folderOptions.push([name, name]);
        const folderSelect = select(folderOptions, folder);
        folderSelect.addEventListener('change', () => { folder = folderSelect.value; void renderNotes(entries); });
        toolbar.append(el('div', 'ma-filter-row', [searchInput, folderSelect]));

        const selectionStatus = el('div', 'ma-selection-status');
        const mergeButton = taskButton('人工合并', () => api.runSummary('merge', [...selected]));
        const manageBar = el('div', 'ma-manage-bar', [
          selectionStatus,
          el('div', 'ma-manage-actions', [
            mergeButton,
            taskButton('设为基石', () => api.runAction('cornerstone', { uids: [...selected], locked: true })),
            taskButton('解除基石', () => api.runAction('cornerstone', { uids: [...selected], locked: false })),
            taskButton('移动文件夹', async () => {
              const name = prompt('输入文件夹名称；留空回到默认分类', '') ?? null;
              if (name !== null) await api.runAction('folder', { uids: [...selected], folder: name });
            }),
            taskButton('定义前', () => api.runAction('position', { uids: [...selected], position: 0 })),
            taskButton('定义后', () => api.runAction('position', { uids: [...selected], position: 1 })),
            taskButton('删除', async () => {
              if (confirm(`删除 ${selected.size} 个条目？`)) await api.runAction('delete', { uids: [...selected] });
            }, 'ma-danger'),
          ]),
        ]);
        const refreshSelection = () => {
          selectionStatus.textContent = `已选择 ${selected.size} 个条目`;
          manageBar.hidden = selected.size === 0;
          mergeButton.disabled = selected.size < 2;
        };
        refreshSelection();
        toolbar.append(manageBar);
        main.append(toolbar);

        if (!filteredCount) main.append(el('div', 'ma-empty', '没有条目'));
        for (const [name, values] of grouped) {
          const block = el('section', 'ma-folder');
          block.append(el('div', 'ma-folder-head', [el('h2', '', name), el('span', 'ma-folder-count', `${values.length} 条`)]));
          for (const entry of values) block.append(entryCard(entry, entries, refreshSelection));
          main.append(block);
        }
      } catch (error) {
        main.replaceChildren(section('世界档案', el('div', 'ma-error', String(error?.message || error))));
      }
    }


    function entryCard(entry, allEntries, refreshSelection) {
      const expanded = String(entry.uid) === expandedUid;
      const card = el('article', `ma-entry-item${expanded ? ' is-expanded' : ''}`);
      const checkbox = document.createElement('input');
      checkbox.type = 'checkbox';
      checkbox.checked = selected.has(String(entry.uid));
      checkbox.addEventListener('change', () => {
        if (checkbox.checked) selected.add(String(entry.uid)); else selected.delete(String(entry.uid));
        card.classList.toggle('is-selected', checkbox.checked);
        refreshSelection();
      });
      checkbox.className = 'ma-entry-check';
      card.classList.toggle('is-selected', checkbox.checked);
      const icon = el('span', 'ma-type-icon', TYPE_ICON[entry.type] || '·');
      const copy = el('span', 'ma-entry-copy', [
        el('strong', '', entry.name),
        el('small', 'ma-entry-status', `${entry.type}${entry.cornerstone ? ' · 基石' : ''}${entry.focus ? ' · 焦点' : ''}${entry.summaryLevel ? ` · ${entry.summaryLevel}` : ''}`),
        el('small', 'ma-keywords', `关键词：${entry.keywords.join('、') || '无'}`),
      ]);
      const open = btn(expanded ? '收起' : '展开', () => { expandedUid = expanded ? '' : String(entry.uid); void renderNotes(allEntries); }, 'ma-quiet ma-entry-open');
      card.append(el('div', 'ma-entry-row', [checkbox, icon, copy, open]));
      if (expanded) card.append(entryDetail(entry));
      return card;
    }

    function entryDetail(entry) {
      const body = el('div', 'ma-detail-body');
      body.append(el('small', 'ma-detail-meta', `UID ${entry.uid} · ${entry.insertionPosition === 0 ? '角色定义前' : '角色定义后'}${entry.folder ? ` · ${entry.folder}` : ''}`));
      const editor = document.createElement('textarea');
      editor.className = 'ma-input ma-editor';
      editor.value = entry.content;
      body.append(editor);

      const buttons = el('div', 'ma-detail-toolbar', [
        taskButton('保存正文', () => api.runAction('edit', { uid: entry.uid, content: editor.value })),
        taskButton(entry.cornerstone ? '解除基石' : '设为基石', () => api.runAction('cornerstone', { uids: [entry.uid], locked: !entry.cornerstone })),
        entry.type === '人物' ? taskButton(entry.focus ? '解除焦点' : '设为焦点', () => api.runAction('focus', { uid: entry.uid, focused: !entry.focus })) : null,
        taskButton('定义前', () => api.runAction('position', { uids: [entry.uid], position: 0 })),
        taskButton('定义后', () => api.runAction('position', { uids: [entry.uid], position: 1 })),
        taskButton('移动文件夹', async () => {
          const name = prompt('输入文件夹名称；留空回到默认分类', entry.folder) ?? null;
          if (name !== null) await api.runAction('folder', { uids: [entry.uid], folder: name });
        }),
        taskButton('删除', async () => { if (confirm(`删除 ${entry.title}？`)) await api.runAction('delete', { uids: [entry.uid] }); }, 'ma-danger'),
      ]);
      body.append(buttons);

      const keywords = input('主要关键词，用、分隔', entry.keywords.join('、'));
      const secondary = input('次关键词，用、分隔', entry.secondaryKeywords.join('、'));
      const constant = document.createElement('input'); constant.type = 'checkbox'; constant.checked = entry.constant;
      const recall = el('div', 'ma-entry-settings', [
        el('strong', '', '召回'), keywords, secondary,
        el('label', 'ma-check-field', [constant, el('span', '', '常驻')]),
        taskButton('保存召回', () => {
          const primary = [];
          const secondaryValues = [];
          for (const value of String(keywords.value || '').split(/[、,，]/u)) if (value.trim()) primary.push(value.trim());
          for (const value of String(secondary.value || '').split(/[、,，]/u)) if (value.trim()) secondaryValues.push(value.trim());
          return api.runAction('recall', {
            uid: entry.uid,
            value: { keywords: primary, secondaryKeywords: secondaryValues, constant: constant.checked },
          });
        }),
      ]);
      body.append(recall);
      return body;
    }
    function renderSettings() {
      const options = api.options();
      const cfg = options.settings;
      main.append(el('div', 'ma-options-head', [el('h1', '', '选项')]));
      const host = section('自动运行');
      host.append(toggle('自动提取', cfg.autoExtraction, value => api.saveSettings({ autoExtraction: value })));
      host.append(toggle('自动审核', cfg.autoAudit, value => api.saveSettings({ autoAudit: value })));
      host.append(toggle('自动小总结', cfg.autoSmallSummary, value => api.saveSettings({ autoSmallSummary: value })));
      host.append(toggle('自动大总结', cfg.autoLargeSummary, value => api.saveSettings({ autoLargeSummary: value })));
      host.append(toggle('未绑定时自动建世界书', cfg.autoCreateLorebook, value => api.saveSettings({ autoCreateLorebook: value })));

      const model = section('模型');
      const profiles = options.profiles;
      const profileOptions = [['', '使用当前 SillyTavern 模型']];
      for (const profile of profiles) profileOptions.push([String(profile.id), String(profile.name || profile.id)]);
      const profileSelect = select(profileOptions, cfg.modelProfileId);
      profileSelect.addEventListener('change', () => api.saveSettings({ modelProfileId: profileSelect.value }));
      const tokens = input('最大输出 Tokens', String(cfg.responseTokens), 'number');
      tokens.addEventListener('change', () => api.saveSettings({ responseTokens: Number(tokens.value) || 8192 }));
      const groups = input('大总结触发批次数', String(cfg.largeSummaryGroups), 'number');
      groups.addEventListener('change', () => api.saveSettings({ largeSummaryGroups: Number(groups.value) || 4 }));
      const audit = document.createElement('textarea');
      audit.className = 'ma-input ma-small-editor';
      audit.placeholder = '审核提示词';
      audit.value = cfg.auditPrompt || '';
      audit.addEventListener('change', () => api.saveSettings({ auditPrompt: audit.value }));
      model.append(profileSelect, tokens, groups, audit, taskButton('测试模型', () => api.runAction('test-model')));

      const maintenance = section('维护', el('div', 'ma-action-grid', [
        taskButton('迁移旧格式条目', () => api.runAction('migrate')),
        taskButton('撤回上次手动操作', () => api.runRollback()),
        taskButton('清空镜渊管理条目', async () => { if (confirm('确定清空当前世界书中的镜渊管理条目？')) await api.runReset(); }, 'ma-danger'),
      ]));
      main.append(host, model, maintenance);
    }

    function toggle(label, checked, change) {
      const inputEl = document.createElement('input');
      inputEl.type = 'checkbox'; inputEl.checked = checked;
      inputEl.addEventListener('change', () => change(inputEl.checked));
      return el('label', 'ma-setting-row', [el('span', '', label), inputEl]);
    }

    function taskButton(label, action, className = '') {
      return btn(label, async event => {
        const button = event.currentTarget;
        button.disabled = true;
        button.classList.add('is-busy');
        try { await action(); }
        catch (error) { alert(String(error?.message || error)); }
        finally { button.disabled = false; button.classList.remove('is-busy'); }
      }, className);
    }

    return {
      refresh: (entries, view = null) => { if (!panel.hidden) void render(entries, view); },
      refreshEntries: entries => { if (!panel.hidden && activeTab === 'notes') void renderNotes(entries); },
      refreshStatus: view => { if (!panel.hidden && activeTab === 'run') void render(null, view); },
    };
  }

  function el(tag, className = '', content = null) {
    const node = document.createElement(tag);
    if (className) node.className = className;
    if (Array.isArray(content)) {
      for (const child of content) if (child) node.append(child);
    } else if (content instanceof Node) {
      node.append(content);
    } else if (content != null) {
      node.textContent = String(content);
    }
    return node;
  }

  function btn(label, action, className = '') {
    const button = el('button', `ma-button ${className}`.trim(), label);
    button.type = 'button';
    button.addEventListener('click', action);
    return button;
  }

  function section(title, body = null) {
    const node = el('section', 'ma-section');
    if (title) node.append(el('h2', '', title));
    if (Array.isArray(body)) {
      for (const child of body) if (child) node.append(child);
    } else if (body) {
      node.append(body);
    }
    return node;
  }

  function input(placeholder, value = '', type = 'text') {
    const node = document.createElement('input');
    node.className = 'ma-input'; node.type = type; node.placeholder = placeholder; node.value = value;
    return node;
  }

  function select(options, value = '') {
    const node = document.createElement('select');
    node.className = 'ma-select';
    for (const [id, label] of options) {
      const option = document.createElement('option'); option.value = id; option.textContent = label; option.selected = String(id) === String(value); node.append(option);
    }
    return node;
  }
  return Object.freeze({ mountUI });
})();

const __ma_module_1 = (() => {
  const { mountUI } = __ma_module_0;
  const KEY = 'mirrorAbyssClean';

  const DEFAULT_SETTINGS = {
    autoAudit: false,
    autoExtraction: true,
    autoSmallSummary: true,
    autoLargeSummary: true,
    autoCreateLorebook: true,
    largeSummaryGroups: 4,
    responseTokens: 8192,
    modelProfileId: '',
    auditPrompt: '',
  };

  const SCHEMA = {
    人物: { replace: ['当前状态'], sections: ['身份', '经历', '当前状态'] },
    场景: { replace: ['状态', '场景阶段'], sections: ['位置', '状态', '场景阶段'] },
    物品: { replace: ['状态', '所属关系'], sections: ['来源', '状态', '所属关系'] },
    事件: { replace: ['事件结果'], sections: ['事件过程', '事件结果', '影响'] },
    世界: { replace: ['环境状态'], sections: ['世界规则', '环境状态', '长期变化'] },
    基础设定: { replace: [], sections: ['世界常识', '自然规则', '种族与生命', '能力与技术', '社会规则', '地理框架', '别名'] },
  };

  const TITLE = /^(人物|场景|物品|事件|世界|基础设定)｜(.+)$/u;
  const SUMMARY = /^整理｜([^｜]+)｜([^｜]+)｜([^｜]+)｜([^｜]+)｜(.+)$/u;
  const PROTOCOL_BRACKETS = { '(': ')', '（': '）', '[': ']', '［': '］', '【': '】' };
  const PROTOCOL_CLOSERS = new Set([')', '）', ']', '］', '】']);
  const FINAL_ONLY = '只输出规定格式，不解释，不输出分析，不使用代码块。';

  let schemaText = '';
  for (const type in SCHEMA) schemaText += `${schemaText ? '\n' : ''}${type}：${SCHEMA[type].sections.join('、')}`;

  function startApplication(initialContext, registerEvents) {
    const state = {
      busy: false,
      status: '等待处理',
      error: '',
      currentScene: '',
      activatedUids: [],
      undo: null,
      lastUids: [],
      cancelVersion: 0,
    };

    let chain = Promise.resolve();
    let ui = null;
    let sequence = [];

    const stateView = live => ({
      busy: state.busy,
      status: state.status,
      error: state.error,
      currentScene: state.currentScene,
      activatedUids: state.activatedUids,
      undo: state.undo ? { label: state.undo.label } : null,
      lastUids: state.lastUids,
      worldbookName: String(live?.chatMetadata?.world_info ?? '').trim(),
    });

    const api = {
      state: () => stateView(currentContext()),
      options: () => {
        const live = currentContext();
        let profiles = [];
        const service = live.ConnectionManagerRequestService;
        if (service?.getSupportedProfiles) {
          try {
            const result = service.getSupportedProfiles() || [];
            if (Array.isArray(result)) profiles = result;
          } catch { profiles = []; }
        }
        return { settings: settings(live), profiles };
      },
      saveSettings(patch) {
        const ctx = currentContext();
        const saved = ctx.extensionSettings?.[KEY] || {};
        const compact = {};
        let changed = false;
        let hasCompact = false;
        for (const key in DEFAULT_SETTINGS) {
          const current = Object.hasOwn(saved, key) ? saved[key] : DEFAULT_SETTINGS[key];
          const value = Object.hasOwn(patch, key) ? patch[key] : current;
          if (!Object.is(value, current)) changed = true;
          if (!Object.is(value, DEFAULT_SETTINGS[key])) { compact[key] = value; hasCompact = true; }
        }
        if (!changed) return;
        ctx.extensionSettings ||= {};
        if (hasCompact) ctx.extensionSettings[KEY] = compact;
        else delete ctx.extensionSettings[KEY];
        ctx.saveSettingsDebounced?.();
      },
      listEntries: async () => {
        const live = currentContext();
        return managedEntries((await readWorldbook(live)).data);
      },
      runFull,
      runSummary,
      runAction,
      runRollback,
      runReset,
      cancel,
    };

    function queue(label, work) {
      const version = state.cancelVersion;
      const job = chain.then(async () => {
        if (version !== state.cancelVersion) return null;
        const live = currentContext();
        state.busy = true;
        state.status = label;
        state.error = '';
        ui?.refreshStatus(stateView(live));
        try {
          const result = await work(version, live);
          if (version === state.cancelVersion) {
            state.status = '完成';
            state.lastUids = Array.isArray(result?.uids) ? result.uids : [];
          }
        } catch (error) {
          if (version === state.cancelVersion) {
            state.status = '失败';
            state.error = String(error?.message || error);
          }
          console.error('[Mirror Abyss]', error);
          throw error;
        } finally {
          if (version === state.cancelVersion) {
            state.busy = false;
            ui?.refreshStatus(stateView(live));
          }
        }
      });
      chain = job.catch(() => undefined);
      return job;
    }

    function cancel(suppliedContext = null) {
      const live = suppliedContext || currentContext();
      state.cancelVersion++;
      state.busy = false;
      state.status = '已取消';
      state.error = '';
      ui?.refreshStatus(stateView(live));
    }

    function runFull(mode = 'full', automatic = false, requestedIndex = -1, presetCfg = null) {
      return queue(automatic ? '自动整理正文' : '整理当前正文', async (version, live) => {
        const chat = live.chat || [];
        const index = latestAssistantIndex(requestedIndex, live);
        const sourceMessage = chat[index];
        let assistantText = String(sourceMessage.mes || '');
        let playerText = '';
        if (mode !== 'audit') {
          for (let i = index - 1; i >= 0; i--) {
            if (chat[i]?.is_user) { playerText = String(chat[i].mes || ''); break; }
          }
        }
        const cfg = presetCfg || settings(live);
        if (mode === 'audit' && !String(cfg.auditPrompt || '').trim()) throw new Error('请先在设置中填写审核提示词');

        if ((mode === 'audit' || (mode === 'full' && cfg.autoAudit)) && String(cfg.auditPrompt || '').trim()) {
          state.status = '审核正文';
          ui?.refreshStatus(stateView(live));
          const auditText = await askModel({
            system: `${cfg.auditPrompt}\n\n符合要求只输出：审核结论：通过\n不符合只输出：\n审核结论：需要修正\n- 明确问题\n${FINAL_ONLY}`,
            user: `待审核正文：\n${assistantText}`,
          }, cfg, live);
          const auditValue = String(auditText || '').trim();
          let audit;
          if (auditValue === '审核结论：通过') {
            audit = { passed: true, issues: [] };
          } else {
            const lines = [];
            for (const raw of auditValue.split(/\r?\n/u)) {
              const line = raw.trim();
              if (line) lines.push(line);
            }
            if (lines[0] !== '审核结论：需要修正') throw new Error('模型返回格式不符合审核约定');
            const issues = [];
            for (let i = 1; i < lines.length; i++) {
              const issue = lines[i].replace(/^[-•]\s*/u, '');
              if (issue) issues.push(issue);
            }
            audit = { passed: false, issues };
          }
          if (version !== state.cancelVersion) return null;
          if (!audit.passed) {
            state.status = '修正正文';
            ui?.refreshStatus(stateView(live));
            let issueText = '';
            for (const issue of audit.issues) issueText += `${issueText ? '\n' : ''}- ${issue}`;
            const revised = await askModel({
              system: `只修正列出的明确问题，其他内容保持不变。直接输出修改后的完整正文。${FINAL_ONLY}`,
              user: `问题：\n${issueText}\n\n原正文：\n${assistantText}`,
            }, cfg, live);
            if (version !== state.cancelVersion) return null;
            const message = live.chat?.[index];
            if (!message || message.is_user || message.is_system) throw new Error('AI 正文已经不存在');
            if (revised !== String(message.mes || '')) {
              message.mes = revised;
              if (Array.isArray(message.swipes) && Number.isInteger(message.swipe_id)) message.swipes[message.swipe_id] = revised;
              live.updateMessageBlock?.(index, message);
              await live.saveChat?.();
            }
            assistantText = revised;
            if (version !== state.cancelVersion) return null;
          }
        }
        if (mode === 'audit') return;

        state.status = '读取世界书';
        ui?.refreshStatus(stateView(live));
        const opened = await readWorldbook(live);
        if (version !== state.cancelVersion) return null;
        const beforeEntries = managedEntries(opened.data);
        const previousScene = state.currentScene || currentScene(beforeEntries);

        state.status = '模型提取';
        ui?.refreshStatus(stateView(live));
        const book = formatEntries(beforeEntries) || '（无）';
        const raw = await askModel({
          system: `你是世界事实整理员。只记录当前AI正文中已经明确发生、会影响后续连续性的事实。不预测，不补全，不把玩家愿望当事实。已有对象必须复用世界书中已有的类型和稳定名称。\n\n允许类型与栏目：\n${schemaText}\n\n固定输出格式示例：\n[旧车站]\n[人物][阿洛][阿洛、值守员、旧车站]\n[身份][阿洛是旧车站值守员]\n[当前状态][阿洛正在检查站台]\n[物品][铜钥匙][铜钥匙、阿洛]\n[所属关系][铜钥匙由阿洛保管]\n\n每个对象后面至少紧跟一条属于它的事实。对象数和每个对象的事实行数不限。\n\n没有事实时只输出：\n[未识别]\n无\n${FINAL_ONLY}`,
          user: `提取前当前场景：${previousScene || '未识别'}\n\n提取前世界书：\n${book}\n\n玩家本轮输入：\n${playerText || '（无）'}\n\n当前AI正文：\n${assistantText}`,
        }, cfg, live);
        if (version !== state.cancelVersion) return null;
        const extractionLines = cleanLines(raw);
        const sceneFields = protocolFields(extractionLines.shift() || '');
        if (sceneFields.length !== 1 || !sceneFields[0]) throw new Error('模型返回格式不符合提取约定');
        let scene = sceneFields[0];
        if (!scene || scene === '未识别') scene = previousScene || '';
        if (!extractionLines.length) throw new Error('模型返回格式不符合事实约定');
        const parsed = {
          scene,
          groups: extractionLines.length === 1 && extractionLines[0].trim() === '无' ? [] : parseFactLines(extractionLines),
        };

        const summaryChanges = [];
        const summaryTouched = [];
        if (automatic && cfg.autoSmallSummary && previousScene && parsed.scene && previousScene !== parsed.scene) {
          const smallSources = [];
          for (const entry of beforeEntries) {
            if (entry.scene === previousScene && !entry.cornerstone && entry.summaryLevel !== 'small' && entry.summaryLevel !== 'large') smallSources.push(entry);
          }
          if (smallSources.length >= 2) {
            state.status = `小总结 · ${previousScene}`;
            ui?.refreshStatus(stateView(live));
            const smallGroups = parseSummary(await askModel(summaryPrompt('small', smallSources), cfg, live), smallSources);
            if (version !== state.cancelVersion) return null;
            const small = applySummary(opened.data, smallSources, smallGroups, { automatic: true, kind: 'small', messageIndex: index });
            summaryChanges.push(...small.changes);
            summaryTouched.push(...small.touched);

            if (cfg.autoLargeSummary) {
              const largeSources = selectLargeSummarySources(managedEntries(opened.data), cfg.largeSummaryGroups, true);
              if (largeSources.length >= 2) {
                state.status = '大总结';
                ui?.refreshStatus(stateView(live));
                const largeGroups = parseSummary(await askModel(summaryPrompt('large', largeSources), cfg, live), largeSources);
                if (version !== state.cancelVersion) return null;
                const large = applySummary(opened.data, largeSources, largeGroups, { automatic: true, kind: 'large', messageIndex: index });
                summaryChanges.push(...large.changes);
                summaryTouched.push(...large.touched);
              }
            }
          }
        }

        const facts = applyFacts(opened.data, parsed.groups, {
          automatic,
          messageIndex: index,
          scene: parsed.scene,
        });
        state.currentScene = parsed.scene;

        let changes = facts.changes;
        let uids = facts.changes.map(change => String(change.uid));
        if (summaryChanges.length) {
          const first = new Map();
          for (const change of summaryChanges) if (!first.has(String(change.uid))) first.set(String(change.uid), change);
          for (const change of facts.changes) if (!first.has(String(change.uid))) first.set(String(change.uid), change);
          changes = [];
          for (const change of first.values()) {
            if (JSON.stringify(opened.data.entries?.[change.uid] ?? null) !== JSON.stringify(change.before)) changes.push(change);
          }
          const touched = new Set(summaryTouched);
          for (const change of facts.changes) touched.add(String(change.uid));
          uids = [];
          for (const change of changes) if (touched.has(String(change.uid))) uids.push(String(change.uid));
        }

        if (changes.length) {
          state.status = '写入世界书';
          ui?.refreshStatus(stateView(live));
          await live.saveWorldInfo(opened.name, opened.data, true);
          if (version !== state.cancelVersion) return null;

          if (index >= 0) {
            const rawHistory = live.chatMetadata?.[KEY]?.history;
            const history = Array.isArray(rawHistory) ? rawHistory : [];
            let at = -1;
            for (let i = 0; i < history.length; i++) {
              if (history[i].messageIndex === index && history[i].worldbookName === opened.name) { at = i; break; }
            }
            if (at < 0) {
              await saveHistory([...history, { messageIndex: index, worldbookName: opened.name, changes }], live);
            } else {
              const known = new Set();
              for (const change of history[at].changes) known.add(String(change.uid));
              const added = [];
              for (const change of changes) if (!known.has(String(change.uid))) added.push(change);
              if (added.length) {
                const next = [...history];
                next[at] = { ...history[at], changes: [...history[at].changes, ...added] };
                await saveHistory(next, live);
              }
            }
          }
        }

        return { uids };
      });
    }

    function runSummary(kind = 'small', uids = [], requirement = '') {
      const label = kind === 'large' ? '大总结' : kind === 'merge' ? '人工合并' : '小总结';
      return queue(label, async (version, live) => {
        const cfg = settings(live);
        const opened = await readWorldbook(live);
        if (version !== state.cancelVersion) return null;
        const entries = managedEntries(opened.data);
        let sources = [];
        if (uids.length) {
          const selected = new Set();
          for (const uid of uids) selected.add(String(uid));
          for (const entry of entries) if (selected.has(String(entry.uid))) sources.push(entry);
          if (sources.length !== selected.size) throw new Error('所选条目已经变化，请重新选择');
        }
        if (!sources.length && kind === 'small') {
          const scene = state.currentScene || currentScene(entries);
          for (const entry of entries) {
            if (entry.scene === scene && !entry.cornerstone && entry.summaryLevel !== 'small' && entry.summaryLevel !== 'large') sources.push(entry);
          }
        }
        if (!sources.length && kind === 'large') sources = selectLargeSummarySources(entries, cfg.largeSummaryGroups);
        if (sources.length < 2) throw new Error('至少需要两个条目');

        const mode = kind === 'merge' ? 'merge' : kind;
        const groups = parseSummary(await askModel(summaryPrompt(mode, sources, requirement), cfg, live), sources);
        if (version !== state.cancelVersion) return null;
        const result = applySummary(opened.data, sources, groups, { automatic: false, kind: mode, messageIndex: -1 });
        if (result.changes.length) {
          await live.saveWorldInfo(opened.name, opened.data, true);
          if (version !== state.cancelVersion) return null;
          state.undo = { label, worldbookName: opened.name, changes: result.changes };
        }
      });
    }

    function runAction(type, payload = {}) {
      const labels = {
        import: '导入世界设定',
        'test-model': '测试模型',
        edit: '更新条目',
        recall: '更新召回',
        cornerstone: payload.locked ? '设置基石' : '解除基石',
        focus: payload.focused ? '设置焦点' : '解除焦点',
        position: '修改定义位置',
        folder: '移动文件夹',
        delete: '删除条目',
        migrate: '迁移旧条目',
      };
      const label = labels[type];
      if (!label) return Promise.reject(new Error(`未知操作：${type}`));

      return queue(label, async (version, live) => {
        if (type === 'test-model') {
          const text = await askModel({ system: '只输出：镜渊连接正常', user: '测试连接' }, null, live);
          if (!text.includes('镜渊连接正常')) throw new Error(`模型返回：${text.slice(0, 80)}`);
          return;
        }

        if (type === 'import') {
          const source = String(payload.text || '').trim();
          if (!source) throw new Error('请先输入世界设定');
          const cfg = settings(live);
          const opened = await readWorldbook(live);
          if (version !== state.cancelVersion) return null;
          const entries = managedEntries(opened.data);
          const book = formatEntries(entries) || '（无）';
          const raw = await askModel({
            system: `把玩家提交的世界设定整理为世界书条目。世界长期通用规则优先放入“基础设定”，具体人物、场景、物品、事件、世界状态按对应类型整理。导入条目之后会由插件设为基石。\n\n允许类型与栏目：\n${schemaText}\n\n固定输出格式示例：\n[人物][石青][石青、北塔测绘师、银罗盘]\n[身份][石青是北塔测绘师]\n[当前状态][石青随身携带银罗盘]\n[物品][银罗盘][银罗盘、石青]\n[所属关系][银罗盘由石青携带]\n\n每个对象后面至少紧跟一条属于它的事实。对象数和每个对象的事实行数不限。\n\n没有可导入内容时只输出“无”。\n${FINAL_ONLY}`,
            user: `玩家提交的世界设定：\n${source}\n\n已有世界书：\n${book}`,
          }, cfg, live);
          if (version !== state.cancelVersion) return null;
          const lines = cleanLines(raw);
          const groups = lines.length === 1 && lines[0].trim() === '无' ? [] : parseFactLines(lines);
          const result = applyFacts(opened.data, groups, { automatic: false, messageIndex: -1, scene: '', cornerstone: true });
          if (result.changes.length) {
            await live.saveWorldInfo(opened.name, opened.data, true);
            if (version !== state.cancelVersion) return null;
            state.undo = { label, worldbookName: opened.name, changes: result.changes };
          }
          return;
        }

        const opened = await readWorldbook(live);
        if (version !== state.cancelVersion) return null;
        let result = { changes: [] };

        if (type === 'focus') {
          const target = opened.data.entries?.[payload.uid];
          const targetTitle = String(target?.comment || '').trim().match(TITLE);
          if (target?.extensions?.mirrorAbyss?.managed !== true || targetTitle?.[1] !== '人物') throw new Error('只有人物条目可以设为焦点');
          for (const uid in (opened.data.entries || {})) {
            const entry = opened.data.entries[uid];
            if (entry?.extensions?.mirrorAbyss?.managed !== true || String(entry.comment || '').trim().match(TITLE)?.[1] !== '人物') continue;
            const yes = String(entry.uid) === String(payload.uid) && Boolean(payload.focused);
            if (entry.extensions.mirrorAbyss.focus === yes && (!yes || entry.constant === true)) continue;
            const before = JSON.stringify(entry);
            entry.extensions.mirrorAbyss.focus = yes;
            if (yes) entry.constant = true;
            result.changes.push({ uid: String(entry.uid), before: JSON.parse(before) });
          }
        } else if (type === 'delete') {
          for (const uid of payload.uids || []) {
            const entry = opened.data.entries?.[uid];
            if (!entry) continue;
            result.changes.push({ uid: String(uid), before: entry });
            delete opened.data.entries[uid];
          }
        } else if (type === 'migrate') {
          let now = 0;
          for (const uid in (opened.data.entries || {})) {
            const raw = opened.data.entries[uid];
            const ext = raw?.extensions?.mirrorAbyss;
            if (ext?.managed === true) {
              const oldPosition = Object.hasOwn(ext, 'insertionPosition');
              if (!oldPosition && !Object.hasOwn(ext, 'messageIndex') && !Object.hasOwn(ext, 'relations')) continue;
              const before = structuredClone(raw);
              if (oldPosition) raw.position = Number(ext.insertionPosition) === 0 ? 0 : 1;
              delete ext.insertionPosition;
              delete ext.messageIndex;
              delete ext.relations;
              result.changes.push({ uid: String(raw.uid), before });
              continue;
            }
            const title = String(raw?.comment || '').trim().match(TITLE);
            if (!title) continue;
            result.changes.push({ uid: String(raw.uid), before: structuredClone(raw) });
            raw.extensions ||= {};
            raw.extensions.mirrorAbyss = {
              managed: true,
              cornerstone: false,
              focus: false,
              folder: '',
              scene: '',
              updatedAt: now || (now = Date.now()),
            };
          }
        } else {
          let uids = [];
          let editContent = '';
          if (type === 'edit') {
            if (!opened.data.entries?.[payload.uid]) throw new Error(`找不到 UID ${payload.uid}`);
            uids = [payload.uid];
            editContent = String(payload.content || '').trim();
          } else if (type === 'recall') uids = [payload.uid];
          else if (type === 'cornerstone') uids = payload.uids || [];
          else if (type === 'position') uids = payload.uids || [];
          else if (type === 'folder') uids = payload.uids || [];
          for (const uid of uids) {
            const entry = opened.data.entries?.[uid];
            if (!entry) continue;
            const before = JSON.stringify(entry);
            if (type === 'edit') entry.content = editContent;
            else if (type === 'recall') {
              const title = String(entry.comment || '').match(TITLE);
              const name = title?.[2]?.trim() || '';
              entry.key = unique([name, entry.comment, ...(payload.value?.keywords || [])]);
              entry.keysecondary = unique(payload.value?.secondaryKeywords || []);
              entry.constant = Boolean(payload.value?.constant);
            } else if (type === 'cornerstone') entry.extensions.mirrorAbyss.cornerstone = Boolean(payload.locked);
            else if (type === 'position') {
              entry.position = Number(payload.position) === 0 ? 0 : 1;
              delete entry.extensions.mirrorAbyss.insertionPosition;
            } else if (type === 'folder') entry.extensions.mirrorAbyss.folder = String(payload.folder || '').trim();
            if (JSON.stringify(entry) !== before) result.changes.push({ uid: String(uid), before: JSON.parse(before) });
          }
        }

        if (result.changes.length) {
          await live.saveWorldInfo(opened.name, opened.data, true);
          if (version !== state.cancelVersion) return null;
          state.undo = { label, worldbookName: opened.name, changes: result.changes };
        }
      });
    }

    function runRollback(kind = 'undo', payload = {}) {
      if (kind === 'undo') {
        const saved = state.undo;
        if (!saved) return Promise.resolve();
        return queue(`撤回 · ${saved.label}`, async (version, live) => {
          if (String(live.chatMetadata?.world_info ?? '').trim() !== saved.worldbookName) throw new Error('当前世界书已经切换');
          const opened = await readWorldbook(live);
          if (version !== state.cancelVersion) return null;
          const changed = rollbackChanges(opened.data, saved.changes);
          if (changed) await live.saveWorldInfo(opened.name, opened.data, true);
          state.undo = null;
        });
      }

      const index = Number(payload.index);
      return queue('撤回聊天操作', async (version, live) => {
        if (!Number.isInteger(index) || index < 0) return;
        const rawHistory = live.chatMetadata?.[KEY]?.history;
        const history = Array.isArray(rawHistory) ? rawHistory : [];
        const book = String(live.chatMetadata?.world_info ?? '').trim();
        const relevant = [];
        const next = [];
        let historyChanged = false;
        for (const item of history) {
          if (item.messageIndex === index) {
            if (item.worldbookName === book) relevant.push(item);
            historyChanged = true;
            continue;
          }
          if (kind === 'delete' && item.messageIndex > index) {
            next.push({ ...item, messageIndex: item.messageIndex - 1 });
            historyChanged = true;
          } else next.push(item);
        }
        if (relevant.length) {
          const opened = await readWorldbook(live);
          if (version !== state.cancelVersion) return null;
          let changed = false;
          for (const item of relevant) if (rollbackChanges(opened.data, item.changes)) changed = true;
          if (changed) await live.saveWorldInfo(opened.name, opened.data, true);
        }
        if (version !== state.cancelVersion) return null;
        if (historyChanged) {
          await saveHistory(next, live);
          if (version !== state.cancelVersion) return null;
        }
        if (payload.reprocess) {
          const message = currentContext().chat?.[index];
          if (message && !message.is_user && !message.is_system && String(message.mes || '').trim()) {
            void runFull('full', true, index).catch(() => {});
          }
        }
      });
    }

    function runReset() {
      return queue('重置镜渊条目', async (version, live) => {
        let removed = 0;
        if (String(live.chatMetadata?.world_info ?? '').trim()) {
          const opened = await readWorldbook(live);
          if (version !== state.cancelVersion) return null;
          for (const uid in (opened.data.entries || {})) {
            if (opened.data.entries[uid]?.extensions?.mirrorAbyss?.managed !== true) continue;
            delete opened.data.entries[uid];
            removed++;
          }
          if (removed) await live.saveWorldInfo(opened.name, opened.data, true);
        }
        if (version !== state.cancelVersion) return null;
        await saveHistory([], live);
        state.undo = null;
        state.currentScene = '';
      });
    }

    function handleHostEvent(name, ...args) {
      if (name === 'MESSAGE_RECEIVED') {
        const live = currentContext();
        sequence = [...(live.chat || [])];
        const cfg = settings(live);
        if (cfg.autoExtraction) void runFull('full', true, messageIndex(args[0]), cfg).catch(() => {});
        return;
      }
      if (name === 'MESSAGE_EDITED' || name === 'MESSAGE_SWIPED') {
        const live = currentContext();
        const kind = name === 'MESSAGE_EDITED' ? 'edit' : 'swipe';
        const index = messageIndex(args[0]);
        const message = live.chat?.[index];
        const pending = kind === 'swipe' && Boolean(message && Array.isArray(message.swipes) && Number.isInteger(message.swipe_id) && message.swipe_id >= message.swipes.length);
        const reprocess = Boolean(!pending && message && !message.is_user && !message.is_system && String(message.mes || '').trim());
        void runRollback(kind, { index, reprocess }).catch(() => {});
        return;
      }
      if (name === 'MESSAGE_DELETED') {
        const live = currentContext();
        const next = [...(live.chat || [])];
        const length = Math.max(sequence.length, next.length);
        let index = Math.max(0, next.length - 1);
        for (let i = 0; i < length; i++) {
          if (sequence[i] !== next[i]) { index = i; break; }
        }
        sequence = next;
        void runRollback('delete', { index }).catch(() => {});
        return;
      }
      if (name === 'CHAT_CHANGED') {
        const live = currentContext();
        cancel(live);
        state.currentScene = '';
        state.activatedUids = [];
        state.undo = null;
        sequence = [...(live.chat || [])];
        const version = state.cancelVersion;
        if (!String(live.chatMetadata?.world_info ?? '').trim()) {
          ui?.refresh([], stateView(live));
          return;
        }
        void readWorldbook(live).then(opened => {
          if (version !== state.cancelVersion) return;
          const entries = managedEntries(opened.data);
          state.currentScene = currentScene(entries);
          ui?.refresh(entries, stateView(live));
        }).catch(() => {
          if (version !== state.cancelVersion) return;
          state.currentScene = '';
          ui?.refresh([], stateView(live));
        });
        return;
      }
      if (name === 'GENERATION_STARTED') {
        const live = currentContext();
        state.activatedUids = [];
        ui?.refreshStatus(stateView(live));
        return;
      }
      if (name === 'WORLD_INFO_ACTIVATED') {
        const live = currentContext();
        const book = String(live.chatMetadata?.world_info ?? '').trim();
        const uids = [];
        for (const entry of Array.isArray(args[0]) ? args[0] : []) {
          if (entry?.world && String(entry.world) !== book) continue;
          const uid = String(entry?.uid ?? '');
          if (uid) uids.push(uid);
        }
        state.activatedUids = uids;
        ui?.refreshStatus(stateView(live));
        return;
      }
      if (name === 'WORLDINFO_UPDATED') {
        const live = currentContext();
        if (args[0] && String(args[0]) !== String(live.chatMetadata?.world_info ?? '').trim()) return;
        ui?.refreshEntries(args[1] ? managedEntries(args[1]) : null);
      }
    }

    // UI is unconditional: if this module runs, the window exists.
    ui = mountUI(api);
    sequence = [...(initialContext.chat || [])];
    ui.refresh(null, stateView(initialContext));
    registerEvents(handleHostEvent);
    const initialVersion = state.cancelVersion;
    if (String(initialContext.chatMetadata?.world_info ?? '').trim()) {
      void readWorldbook(initialContext).then(opened => {
        if (initialVersion !== state.cancelVersion) return;
        state.currentScene = currentScene(managedEntries(opened.data));
        ui?.refreshStatus(stateView(initialContext));
      }).catch(() => {
        if (initialVersion !== state.cancelVersion) return;
        state.currentScene = '';
        ui?.refreshStatus(stateView(initialContext));
      });
    }
  }

  function currentContext() {
    const getContext = globalThis.SillyTavern?.getContext;
    if (typeof getContext !== 'function') throw new Error('SillyTavern 尚未就绪');
    return getContext();
  }

  function settings(ctx) {
    const saved = ctx.extensionSettings?.[KEY] || {};
    return { ...DEFAULT_SETTINGS, ...saved };
  }

  async function readWorldbook(ctx) {
    let target = String(ctx.chatMetadata?.world_info ?? '').trim();
    if (!target) {
      if (ctx.extensionSettings?.[KEY]?.autoCreateLorebook === false) throw new Error('当前聊天没有绑定世界书');
      const chat = String(ctx.getCurrentChatId?.() ?? ctx.chatId ?? '');
      const base = `镜渊-${String(chat || '世界书').replace(/[\\/:*?"<>|]/g, '-').slice(0, 80) || '世界书'}`;
      const names = new Set((await ctx.getWorldInfoNames?.()) ?? []);
      target = base;
      let index = 2;
      while (names.has(target)) target = `${base}-${index++}`;
      const data = { entries: {} };
      await ctx.saveWorldInfo(target, data, true);
      ctx.chatMetadata ||= {};
      ctx.chatMetadata.world_info = target;
      await ctx.saveMetadata?.();
      return { name: target, data };
    }
    const response = await fetch('/api/worldinfo/get', {
      method: 'POST',
      headers: ctx.getRequestHeaders(),
      cache: 'no-cache',
      body: JSON.stringify({ name: target }),
    });
    if (!response.ok) throw new Error(`读取世界书失败：HTTP ${response.status}`);
    const data = await response.json();
    data.entries ||= {};
    return { name: target, data };
  }

  function latestAssistantIndex(requested, ctx) {
    const chat = ctx.chat || [];
    let index = Number(requested);
    if (!Number.isInteger(index) || index < 0) {
      index = chat.length - 1;
      while (index >= 0 && (chat[index]?.is_user || chat[index]?.is_system || !String(chat[index]?.mes || '').trim())) index--;
    }
    const message = chat[index];
    if (!message || message.is_user || message.is_system) throw new Error('没有可处理的 AI 正文');
    return index;
  }

  async function askModel(prompt, cfg, ctx) {
    cfg ||= settings(ctx);
    let output;
    if (cfg.modelProfileId && ctx.ConnectionManagerRequestService?.sendRequest) {
      output = await ctx.ConnectionManagerRequestService.sendRequest(
        cfg.modelProfileId,
        [
          { role: 'system', content: String(prompt.system || '') },
          { role: 'user', content: String(prompt.user || '') },
        ],
        Number(cfg.responseTokens) || 8192,
        { stream: false, extractData: true, includePreset: true, includeInstruct: true },
        {},
      );
    } else {
      if (typeof ctx.generateRaw !== 'function') throw new Error('SillyTavern 未提供模型调用接口');
      output = await ctx.generateRaw({
        systemPrompt: String(prompt.system || ''),
        prompt: String(prompt.user || ''),
        responseLength: Number(cfg.responseTokens) || 8192,
        trimNames: false,
      });
    }
    const text = typeof output === 'string'
      ? output
      : output?.content ?? output?.text ?? output?.response ?? output?.choices?.[0]?.message?.content ?? output?.choices?.[0]?.text;
    if (!String(text || '').trim()) throw new Error('模型没有返回内容');
    return String(text).trim();
  }

  function messageIndex(value) {
    const raw = typeof value === 'object' ? value?.messageId ?? value?.mesId ?? value?.index : value;
    const number = Number(raw);
    return Number.isInteger(number) && number >= 0 ? number : -1;
  }

  async function saveHistory(history, ctx) {
    const current = ctx.chatMetadata?.[KEY]?.history;
    if (!history.length && !Array.isArray(current)) return;
    ctx.chatMetadata ||= {};
    if (history.length) {
      ctx.chatMetadata[KEY] ||= {};
      ctx.chatMetadata[KEY].history = history;
    } else {
      delete ctx.chatMetadata[KEY];
    }
    await ctx.saveMetadata?.();
  }

  function summaryPrompt(kind, entries, requirement = '') {
    const label = kind === 'large' ? '长期大总结' : kind === 'merge' ? '人工合并' : '当前场景小总结';
    const source = formatEntries(entries, true);
    return {
      system: `${label}。只整理来源中已经存在的事实，不新增事实。允许把多个来源合并成更少、更完整的条目。\n\n允许类型与栏目：\n${schemaText}\n\n每条输出：整理｜条目编号（可多个，用、分隔）｜类型｜稳定名称｜栏目｜完整事实\n必须覆盖全部来源。${kind === 'merge' ? '人工合并后的目标数必须少于来源数。' : ''}\n${FINAL_ONLY}`,
      user: `${requirement ? `玩家要求：${requirement}\n\n` : ''}来源：\n${source}`,
    };
  }

  function formatEntries(entries, numbered = false) {
    let text = '';
    for (let i = 0; i < entries.length; i++) {
      const entry = entries[i];
      const value = `${numbered ? `条目${i + 1}\n` : ''}${entry.title}\n${entry.content}`;
      text += `${text ? '\n\n' : ''}${value}`;
    }
    return text;
  }

  function parseSummary(text, sources) {
    const lines = cleanLines(text);
    if (!lines.length) throw new Error('模型没有返回总结条目');
    const groups = new Map();
    const covered = Array(sources.length).fill(0);
    for (const line of lines) {
      const match = line.match(SUMMARY);
      if (!match) throw new Error('模型返回格式不符合总结约定');
      const indexes = [];
      for (const value of match[1].split(/[、,，]/u)) {
        const ref = value.trim();
        if (!ref) continue;
        const index = Number(ref.replace('条目', '')) - 1;
        if (!Number.isInteger(index) || index < 0 || index >= sources.length) throw new Error('模型返回了不存在的条目编号');
        indexes.push(index);
      }
      if (!indexes.length) throw new Error('模型没有返回来源条目');
      const type = match[2].trim();
      const name = match[3].trim();
      const section = match[4].trim();
      const fact = match[5].trim();
      if (!SCHEMA[type]) throw new Error('模型返回了未知条目类型');
      const key = `${indexes.join(',')}|${type}｜${name}`;
      let group = groups.get(key);
      if (!group) {
        for (const index of indexes) if (++covered[index] > 1) throw new Error('模型重复处理了同一个来源条目');
        group = { indexes, type, name, title: `${type}｜${name}`, sections: {} };
      }
      group.sections[section] ||= [];
      if (!group.sections[section].includes(fact)) group.sections[section].push(fact);
      groups.set(key, group);
    }
    if (covered.some(count => count !== 1)) throw new Error('模型没有覆盖全部来源条目');
    return [...groups.values()];
  }

  function managedEntries(data) {
    const result = [];
    for (const uid in (data.entries || {})) {
      const raw = data.entries[uid];
      const title = String(raw?.comment || '').trim().match(TITLE);
      if (!title || raw?.extensions?.mirrorAbyss?.managed !== true) continue;
      const ext = raw.extensions.mirrorAbyss;
      result.push({
        uid: String(raw.uid),
        type: title[1],
        name: title[2].trim(),
        title: `${title[1]}｜${title[2].trim()}`,
        content: stripRelationBlock(raw.content),
        keywords: unique(raw.key),
        folder: String(ext.folder || ''),
        cornerstone: ext.cornerstone === true,
        focus: ext.focus === true,
        insertionPosition: Number(ext.insertionPosition ?? raw.position ?? 1) === 0 ? 0 : 1,
        scene: String(ext.scene || ''),
        updatedAt: Number(ext.updatedAt || 0),
        summaryLevel: String(ext.summaryLevel || ''),
        summaryBatch: Number(ext.summaryBatch || 0),
        constant: raw.constant === true,
        secondaryKeywords: unique(raw.keysecondary),
        raw,
      });
    }
    return result.sort((a, b) => a.type.localeCompare(b.type, 'zh-CN') || a.name.localeCompare(b.name, 'zh-CN'));
  }

  function currentScene(entries) {
    let latest = null;
    for (const entry of entries) {
      if (entry.scene && (!latest || entry.updatedAt > latest.updatedAt)) latest = entry;
    }
    return latest?.scene || '';
  }

  function applyFacts(data, groups, options = {}) {
    const changes = [];
    if (!groups.length) return { changes };
    const byTitle = new Map();
    for (const uid in (data.entries || {})) {
      const raw = data.entries[uid];
      if (raw?.extensions?.mirrorAbyss?.managed === true) byTitle.set(String(raw.comment || '').trim(), raw);
    }
    let now = 0;
    for (const group of groups) {
      const title = `${group.type}｜${group.name}`;
      let raw = byTitle.get(title);
      if (raw?.extensions?.mirrorAbyss?.cornerstone && options.automatic) continue;
      const before = raw ? JSON.stringify(raw) : null;
      if (!raw) {
        let uid = 0;
        while (Object.hasOwn(data.entries, uid)) uid++;
        raw = {
          uid,
          key: [], keysecondary: [], comment: '', content: '',
          constant: false, vectorized: false, selective: true, selectiveLogic: 0,
          addMemo: false, order: 100, position: 1, disable: false, ignoreBudget: false,
          excludeRecursion: true, preventRecursion: true,
          matchPersonaDescription: false, matchCharacterDescription: false, matchCharacterPersonality: false,
          matchCharacterDepthPrompt: false, matchScenario: false, matchCreatorNotes: false,
          delayUntilRecursion: 0, probability: 100, useProbability: true, depth: 4,
          outletName: '', group: '', groupOverride: false, groupWeight: 100,
          scanDepth: null, caseSensitive: null, matchWholeWords: null, useGroupScoring: null,
          automationId: '', role: 0, sticky: null, cooldown: null, delay: null, triggers: [], extensions: {},
        };
        data.entries[uid] = raw;
        byTitle.set(title, raw);
      }
      const sections = {};
      let section = '';
      for (const rawLine of stripRelationBlock(raw.content).split(/\r?\n/u)) {
        const line = rawLine.trim();
        const heading = line.match(/^【(.+)】$/u);
        if (heading) { section = heading[1].trim(); sections[section] ||= []; continue; }
        const fact = line.match(/^-\s*(.+)$/u);
        if (fact && section) sections[section].push(fact[1].trim());
      }
      for (const row of group.rows) {
        const oldFacts = sections[row.section] || [];
        if (SCHEMA[group.type].replace.includes(row.section)) sections[row.section] = [row.fact];
        else if (!oldFacts.includes(row.fact)) { oldFacts.push(row.fact); sections[row.section] = oldFacts; }
      }
      fillEntry(raw, group.type, group.name, sections, group.keywords, {
        scene: options.scene,
        summaryLevel: '',
        summaryBatch: 0,
      });
      if (options.cornerstone) raw.extensions.mirrorAbyss.cornerstone = true;
      if (before !== null && JSON.stringify(raw) === before) continue;
      raw.order = orderFor(group.type, options.messageIndex);
      raw.extensions.mirrorAbyss.updatedAt = now || (now = Date.now());
      changes.push({ uid: String(raw.uid), before: before === null ? null : JSON.parse(before) });
    }
    return { changes };
  }

  function applySummary(data, sources, groups, options = {}) {
    const beforeByUid = new Map();
    const touched = options.automatic ? [] : null;
    const touchedSet = options.automatic ? new Set() : null;
    const now = Date.now();
    const capture = (uid, before) => {
      const key = String(uid);
      if (!beforeByUid.has(key)) beforeByUid.set(key, before == null ? null : JSON.stringify(before));
    };

    for (const group of groups) {
      const groupSources = [];
      for (const index of group.indexes) groupSources.push(sources[index]);
      for (const source of groupSources) capture(source.uid, source.raw);

      const targetUid = groupSources[0].uid;
      for (const source of groupSources) {
        if (String(source.uid) !== String(targetUid)) delete data.entries[source.uid];
      }

      let raw = data.entries[targetUid];
      if (!raw) {
        raw = structuredClone(groupSources[0].raw);
        raw.uid = Number.isNaN(Number(targetUid)) ? targetUid : Number(targetUid);
        data.entries[targetUid] = raw;
      }

      const keywordValues = [];
      let scene = '';
      for (const entry of groupSources) {
        keywordValues.push(...entry.keywords);
        if (!scene && entry.scene) scene = entry.scene;
      }
      fillEntry(raw, group.type, group.name, group.sections, keywordValues, {
        scene,
        summaryLevel: options.kind || 'small',
        summaryBatch: now,
      });
      raw.order = orderFor(group.type, options.messageIndex);
      raw.extensions.mirrorAbyss.updatedAt = now;
      const key = String(raw.uid);
      if (touched && !touchedSet.has(key)) { touchedSet.add(key); touched.push(key); }
    }
    const changes = [];
    for (const [uid, before] of beforeByUid) {
      const current = data.entries?.[uid] ?? null;
      if ((current == null ? null : JSON.stringify(current)) !== before) changes.push({ uid, before: before == null ? null : JSON.parse(before) });
    }
    return touched ? { changes, touched } : { changes };
  }

  function rollbackChanges(data, changes) {
    let changed = false;
    for (let i = changes.length - 1; i >= 0; i--) {
      const change = changes[i];
      const current = data.entries?.[change.uid] ?? null;
      if (JSON.stringify(current) === JSON.stringify(change.before)) continue;
      if (change.before == null) delete data.entries[change.uid];
      else data.entries[change.uid] = structuredClone(change.before);
      changed = true;
    }
    return changed;
  }

  function selectLargeSummarySources(entries, groupCount = 4, requireFull = false) {
    const count = Math.max(2, Number(groupCount) || 4);
    const selected = new Set();
    const result = [];
    for (const entry of entries) {
      if (entry.summaryLevel !== 'small' || entry.cornerstone || !entry.summaryBatch) continue;
      if (!selected.has(entry.summaryBatch) && selected.size < count) selected.add(entry.summaryBatch);
      if (selected.has(entry.summaryBatch)) result.push(entry);
    }
    return requireFull && selected.size < count ? [] : result;
  }

  function parseFactLines(lines) {
    if (!lines.length) throw new Error('模型返回格式不符合事实约定');
    const groups = new Map();
    let active = null;
    let needsFact = false;
    for (const line of lines) {
      const fields = protocolFields(line);
      if (fields.length === 3) {
        if (needsFact) throw new Error('模型返回格式不符合事实约定');
        const type = fields[0];
        const name = fields[1];
        if (!SCHEMA[type]) throw new Error('模型返回了未知条目类型');
        if (!name || !fields[2]) throw new Error('模型返回格式不符合事实约定');
        const key = `${type}｜${name}`;
        const group = groups.get(key) || { type, name, title: key, keywords: [], rows: [] };
        group.keywords.push(...fields[2].split(/[、,，]/u));
        groups.set(key, group);
        active = group;
        needsFact = true;
        continue;
      }

      if (fields.length !== 2 || !active || !fields[0] || !fields[1]) {
        throw new Error('模型返回格式不符合事实约定');
      }
      const section = fields[0];
      const fact = fields[1];
      const group = active;
      group.rows.push({ section, fact });
      needsFact = false;
    }
    if (needsFact) throw new Error('模型返回格式不符合事实约定');
    return [...groups.values()];
  }

  function protocolFields(line) {
    const text = String(line || '').trim();
    const fields = [];
    let index = 0;
    while (index < text.length) {
      while (/\s/u.test(text[index] || '')) index++;
      const closer = PROTOCOL_BRACKETS[text[index]];
      if (!closer) return [];
      const start = ++index;
      const stack = [closer];
      while (index < text.length && stack.length) {
        const char = text[index++];
        const nestedCloser = PROTOCOL_BRACKETS[char];
        if (nestedCloser) stack.push(nestedCloser);
        else if (PROTOCOL_CLOSERS.has(char)) {
          if (char !== stack.at(-1)) return [];
          stack.pop();
        }
      }
      if (stack.length) return [];
      const value = text.slice(start, index - 1).trim();
      if (!value) return [];
      fields.push(value);
    }
    return fields;
  }

  function fillEntry(raw, type, name, sections, keywords = [], extra = {}) {
    raw.comment = `${type}｜${name}`;
    const lines = [];
    for (const section in (sections || {})) {
      const values = unique(sections[section]);
      if (!values.length) continue;
      lines.push(`【${section}】`);
      for (const fact of values) lines.push(`- ${fact}`);
      lines.push('');
    }
    raw.content = lines.join('\n').trim();
    raw.key = unique([name, raw.comment, ...keywords]);
    raw.selective = true;
    raw.selectiveLogic = 0;
    raw.excludeRecursion = true;
    raw.preventRecursion = true;
    raw.depth = 4;
    raw.position = Number(raw?.extensions?.mirrorAbyss?.insertionPosition ?? raw.position ?? 1) === 0 ? 0 : 1;
    raw.extensions ||= {};
    const ext = raw.extensions.mirrorAbyss ||= {};
    ext.managed = true;
    ext.cornerstone = ext.cornerstone === true;
    ext.focus = ext.focus === true;
    ext.folder = String(ext.folder || '');
    ext.scene = String(extra.scene ?? ext.scene ?? '');
    ext.summaryLevel = String(extra.summaryLevel ?? ext.summaryLevel ?? '');
    ext.summaryBatch = Number(extra.summaryBatch ?? ext.summaryBatch ?? 0);
    delete ext.insertionPosition;
    delete ext.messageIndex;
    delete ext.relations;
    if (type === '基础设定' || ext.focus) raw.constant = true;
  }

  function stripRelationBlock(content) {
    const value = String(content || '');
    const index = value.indexOf('\n【镜渊关系】\n');
    return (index < 0 ? value : value.slice(0, index)).trim();
  }

  function orderFor(type, messageIndexValue = -1) {
    const base = { 基础设定: 0, 世界: 1000, 场景: 2000, 人物: 3000, 物品: 4000, 事件: 5000 }[type] || 6000;
    const index = Number(messageIndexValue);
    return base + (Number.isInteger(index) && index >= 0 ? Math.min(index, 999) : 0);
  }

  function cleanLines(text) {
    const result = [];
    const value = String(text || '').replace(/<think>[\s\S]*?<\/think>/giu, '').replace(/```(?:\w+)?/gu, '');
    for (const raw of value.split(/\r?\n/u)) {
      const line = raw.trim();
      if (line) result.push(line);
    }
    return result;
  }

  function unique(values) {
    const result = [];
    const seen = new Set();
    for (const value of values || []) {
      const text = String(value || '').trim();
      if (!text || seen.has(text)) continue;
      seen.add(text);
      result.push(text);
    }
    return result;
  }
  return Object.freeze({ startApplication });
})();

const { startApplication } = __ma_module_1;

export { startApplication };

